### ISSUE TITLE
Model Body Responses Not Up to JSON-api spec 1.0

### ISSUE THREAD

**Issue by zachncst** [katharsis-project/katharsis-core#100]
Models are being returned from katharsis missing the type, id and parameters objects under data. In it's place is just a data object with key-value pairs.

What is being returned:
```
{
  "data": {
    "id": 2,
    "name": "Foo"
  },
  "jsonPath": {
    "elementName": "customer",
    "ids": {
      "ids": [
        "schooldude.com"
      ]
    },
    "parentResource": null,
    "childResource": null,
    "resourceName": "customer",
    "collection": false
  },
  "requestParams": {
    "filters": null,
    "sorting": null,
    "grouping": null,
    "pagination": null,
    "includedFields": null,
    "includedRelations": null
  },
  "metaInformation": null,
  "linksInformation": null
}
```

What I expect (http://jsonapi.org/format/):
```
{
  "data": {
    "type": "customer",
    "id": "2",
    "attributes": {
      // ... this article's attributes
    },
    "relationships": {
      // ... this article's relationships
    }
  }
}
```

**Comment by meshuga** [comment]
It seems like there are no Jackson serializers registered.

**Comment by zachncst** [comment]
Just to clear it up, we're using the Katharsis-Servlet which provides an object mapper override. This is with the assumption that any object mappers that Katharsis needs to work would be registered to the component. This does not happen. For now I've just removed my object mapper and this seems to fix it.
