### ISSUE TITLE
Feature request: Add an authentication context (or user param) to repository interfaces

### ISSUE THREAD

**Issue by bquenin** [katharsis-project/katharsis-core#102]
Hi,

I'm using katharsis with ratpack and after a few tweaks, it works like a charm.
However, I'm facing an issue with authentication. I have authentication support in my API and I'd like to forward the authenticated user down to the repository level (`ResourceRepository`) in order constrain the database access (create, read, update, delete). Indeed, I want to make sure that the "requester" has the actual right to perform such an action.
With the current `ResourceRepository` and `RelationshipRepository` method signature, there is no way to provide requester (i.e. authenticated user) information.

Do you think it would be possible to modify these interfaces in order to provide this information?

Thanks,
BQ.

**Comment by meshuga** [comment]
Thanks for the issue. I've been thinking about it for some time and created a new issue that could help you doing that: #103.
I close the issue and hope I'll implement this feature, looks like a big challenge :D
