### ISSUE TITLE
Injection of custom resource parameters

### ISSUE THREAD

**Issue by meshuga** [katharsis-project/katharsis-core#103]
It should be possible to inject additional method parameters using a service locator with request context. It means that it will be possible to inject e.g. authentication context. 
An example of a method:
```java
public Task findOne(String id, Authentication authentication) {
  ...
}
public Task findAll(@Named("property1") String someProperty, @Named("property2") String otherProperty) {
  ...
}
```
Note that there's no `@Override` annotation. Some code to access a concrete method need to be implemented. Additionally, there's no `RequestParams requestParams` parameter. It should be an optional parameter.

Each class that will implement functionality for a resource (e.g. save) should be annotated with `@ResourceRepository` annotation, which will define for which resource there are defined methods.

Each method that will execute concrete operations from `ResourceRepository` interface should have proper annotation, that is:
- `@JsonApiFindOne` for `findOne` method
- `@JsonApiFindAll` for `findAll` method
- `@JsonApiSave` for `save` method
- `@JsonApiDelete` for `delete` method

An instance of a new interface `JsonServiceLocator` should be be provided to the Katharsis to provide additional instances of parameters. The draft of the interface:
```java
public interface RepositoryMethodParameterProvider {
  <T> T provide(Parameter parameter);
}
```

RequestDispatcher should pass an instance of `RepositoryMethodParameterProvider`. Each implementation (katharsis-rs, katharsis-servlet, ...) will be able to implement this interface to provide concrete instances of object in request context.

See: https://github.com/katharsis-project/katharsis-core/issues/102

**Comment by bquenin** [comment]
For your information, I managed to inject my authentication context using Guice without modifying the katharsis interfaces.
I'm using ratpack and here is the thread discussing the solution on how to achieve this (with ratpack): http://forum.ratpack.io/Injecting-context-into-a-quot-service-quot-td1300.html

**Comment by meshuga** [comment]
@bquenin Thanks for the solution for ratpack.
I have an idea of creating a set of annotations that can be used to define repository methods: https://github.com/katharsis-project/katharsis-core/tree/katharsis-core-103/src/main/java/io/katharsis/repository/annotations

Introduction of those annotations will break the ResourceRepository interface definition (one method is removed), so I think the next version of Katharsis will be 2.0.0 :)

**Comment by corrspt** [comment]
@meshuga Are you thinking of the same route for Relationships? Using annotations to mark the methods? (It would reduce the number of files needed).

**Comment by meshuga** [comment]
Yes, but first I'd like to implement it for Repository to gain some oversight for the solution :)
