### ISSUE TITLE
Updating an entity and setting a relation to null

### ISSUE THREAD

**Issue by corrspt** [katharsis-project/katharsis-core#104]
Hi, me again :)

I'm trying to update and entity and remove a relation that it previously had (make it null). Using Katharsis 1.0.0 with EmberJS 2.0 + Ember DATA 2.0 (supposed to be JSONAPI compliant.

I do something like this in my javascript code:

```js
var model = this.get('model')
model.set('grade', null)
model.save().then() //....
```
This is the JSON sent by EmberData when I save my model

```javascript
{
  "data": {
    "id": "3",
    "attributes": {
      "description": "Testing"
    },
    "relationships": {
      "code": {
        "data": {
          "type": "codes",
          "id": "2"
        }
      },
      "specification": {
        "data": {
          "type": "specifications",
          "id": "6"
        }
      },
      "grade": {
        "data": null // <---- Trying to remove this
      },
      "material-group": {
        "data": {
          "type": "groups",
          "id": "1"
        }
      }
    },
    "type": "materials"
  }
}
```

What I get is this stack trace
```java
Caused by: java.lang.NullPointerException: null
	at io.katharsis.dispatcher.controller.resource.ResourceUpsert.saveRelations(ResourceUpsert.java:55) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.dispatcher.controller.resource.ResourcePatch.handle(ResourcePatch.java:68) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:42) ~[katharsis-core-1.0.0.jar:na]
	at controllers.JSONAPI.getJsonApiResult(JSONAPI.java:97) ~[classes/:2.4.2]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$8$$anonfun$apply$8.apply(Routes.scala:343) ~[classes/:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$8$$anonfun$apply$8.apply(Routes.scala:343) ~[classes/:na]
```

Debugging the issue I see that in the ResourceUpsert.saveRelations we have:

```java
for (Map.Entry<String, Object> property : additionalProperties.entrySet()) {
                if (Iterable.class.isAssignableFrom(property.getValue().getClass())) {
                    //noinspection unchecked
                    saveRelationsField(savedResource, registryEntry, (Map.Entry) property, registryEntry.getResourceInformation());
                } else {
                    //noinspection unchecked
                    saveRelationField(savedResource, registryEntry, (Map.Entry) property, registryEntry.getResourceInformation());
                }

            }
```

The additionalProperties map has the various properties with values, but with `grade=null` when it reaches the `Iterable.class.isAssignableFrom(property.getValue().getClass()` line, since `grade` is null, it blows up with a `NullPointerException`. 

I couldn't really understand from the JSONAPI spec If the issue is with ember data or with katharsis. What would be katharsis expecting to set a relation to null?

Many thanks for the library once again, sorry for being a pain :(

**Comment by tuomole** [comment]
I'm also using Ember with Katharsis, and noticed the same thing with `io.katharsis.dispatcher.controller.resource.ResourcePost`. If I try to save null to a property, Katharsis throws `NullPointerException`:

```java
if (Iterable.class.isAssignableFrom(property.getValue().getClass())) {
                    //noinspection unchecked
                    setRelationsField(newResource, registryEntry, (Map.Entry) property, requestParams);
                } else {
                    //noinspection unchecked
                    setRelationField(newResource, registryEntry, (Map.Entry) property, requestParams);
                }
```

**Comment by meshuga** [comment]
Thanks for the info!
Should work now

**Comment by corrspt** [comment]
@meshuga. Thanks for all the hard work you and the rest of the guys put on this great project. Truly thanks for the very quick replies and fixes you guys are making. This project is looking good and I'll continue and report any issues I find.

If there's any other way I can be of help, please let me know.

Best regards

**Comment by valimaggi** [comment]
Is this fix coming to Maven repository soon? Thank you.

**Comment by corrspt** [comment]
I also am interested in a maven push of this fix. As I'm deploying to heroku it makes it much easier to have the updates on maven. On the other side I understand that you guys may not want to push every fix as a new release... any recommendations on this situation? Do I pull the code locally and build locally and then add the jar to my project?

Thanks!

**Comment by meshuga** [comment]
hmmm, ok, 
I'll publish version 1.0.1

**Comment by valimaggi** [comment]
@meshuga This is great, thank you!
