### ISSUE TITLE
LinkageContainer triggering ResourceNotFoundInitializationException

### ISSUE THREAD

**Issue by broglep-koubachi** [katharsis-project/katharsis-core#119]
In [RelationshipsResourceGet.java:93](https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/dispatcher/controller/resource/RelationshipsResourceGet.java#L93) a resource response is created using ```LinkageContainer```.
During the serialization in [ContainerSerializer.java#L60](https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/jackson/serializer/ContainerSerializer.java#L60-L65) the dataClass resolves to ```LinkageContainer```and the resource repository throws an exception as there is no such resource.

**Comment by meshuga** [comment]
thanks for the issue!
