### ISSUE TITLE
Deleting to-one relationships fails with NPE

### ISSUE THREAD

**Issue by broglep-koubachi** [katharsis-project/katharsis-core#120]
The specified way to delete a to-one relationship by sending a ```"data":null``` (see http://jsonapi.org/format/#crud-updating-to-one-relationships) results in a NPE in [RelationshipsResourcePatch.java:L39](https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/dispatcher/controller/resource/RelationshipsResourcePatch.java#L39)

**Comment by meshuga** [comment]
thanks for the issue!
