### ISSUE TITLE
New resource creation returns 200 (OK) rather than 201 (Created)

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#126]
Having looked at the specification (http://jsonapi.org/format/#crud-creating), I expected the return from a successful resource creation to be a 201.  Instead, I'm seeing a 200.  Looking at the code, it appears that ResourceResponse responses always return a 200.  The specification also says that the response *should* return a Location header, but I can see the full response, so at least that gets me the ID.  This is with version 1.0.1 of Katharsis, although looking at the code on Github I don't see any recent changes that would affect this behavior.

I don't see this as a huge issue, but seemed worth submitting.

**Comment by meshuga** [comment]
Hey, that's a good point. We'll do it.
