### ISSUE TITLE
Boolean property with is*() getter is misinterpreted.

### ISSUE THREAD

**Issue by simmons** [katharsis-project/katharsis-core#128]
When Katharsis is building a registry of resource classes, it can be thrown off by a class using a boolean property with an is*() getter method.  For example, if a class has a boolean property "enabled", and corresponding isEnabled() and setEnabled() methods, Katharsis will internally see these as two properties -- "enabled" and "nabled".

This is because the ResourceFieldNameTransformer::getName(Method method) method is hard-coded to expect the property name to start at the 3rd character of the method name:

```
public String getName(Method method) {
    String resourceName = method.getName().substring(3);
    String name = resourceName.substring(0, 1).toLowerCase() + resourceName.substring(1);
```

This misinterpretation causes problems later when Katharsis cannot access the misinterpreted property name.  Changing the resource class's getter from isEnabled() to getEnabled() successfully works around the problem.

**Comment by meshuga** [comment]
Thanks for the issue!
