### ISSUE TITLE
Inconsistency in identifier handling in 2.0.0 code

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#135]
While testing #131 (via #119) I updated my codebase to match the changes to the ResourceRepository interface.  As part of the changes, the findAll method that accepted a list of identifiers defined as generic type "ID" was removed in favor of the identifiers inside of the RequestParams object.  That object holds a list of String objects, while my identifiers are of type Long.  However, the RelationshipRepository interface still works in terms of Long values.  The 1.0 means of dealing in properly typed identifiers was much easier to deal with, however having the two interfaces working so differently is pretty inconsistent.  Would it be possible for RequestParams to be typed to match ID type?  For instance:

Iterable<T> findAll(RequestParams<ID> requestParams);

to allow the identifiers to be properly typed even in the findAll call?

**Comment by meshuga** [comment]
I got rid of `findAll` method with a list of identifiers because I suspected that no one uses it plus I thought it might be better than creating a new annotation like `@FindAllWithIds`.
I agree with you, it's inconsistent and additionally breaks repository compatibility. I'll restore the method and add a new annotation.

**Comment by csetera** [comment]
What would the new annotation drive?  I guess I don't have an issue with removing the method overall... but there definitely seemed to be some inconsistency that I didn't quite understand with the string identifiers in the request parameters object.

**Comment by meshuga** [comment]
The identifiers are passed with the request as path parameters and the rest of the fields in `RequestParams` are query parameters + with 2.0.0 `RequestParams` will be renamed to `QueryParams`
