### ISSUE TITLE
Ignoring properties requires JsonIgnore on both field and method

### ISSUE THREAD

**Issue by broglep-koubachi** [katharsis-project/katharsis-core#146]
In [ResourceInformationBuilder.java:80](https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/resource/information/ResourceInformationBuilder.java#L80) both the class fields and the methods are merged together. So if you have a field that is ignored, but still has a getter, it is nonetheless added to the JSON.

**Comment by meshuga** [comment]
Thanks for the issues, I'll merge annotations from fields and getters.
