### ISSUE TITLE
Refactor RepositoryMethodParameterProvider

### ISSUE THREAD

**Issue by meshuga** [katharsis-project/katharsis-core#157]
`RepositoryMethodParameterProvider` should accept a method and a parameter's index to operate. Spring `HandlerMethodArgumentResolver` requires an instance of `MethodParameter` which uses a reference to repository method.

**Comment by corrspt** [comment]
@meshuga Since this is one the v2.0.0 release, but I can't seem to find it on the docs,  nor can I figure out how to use it from the tests you guys have... can we have an example of this, for what purpose it exists and how to use it?

Thanks :muscle:
