### ISSUE TITLE
Support for files

### ISSUE THREAD

**Issue by cgrossde** [katharsis-project/katharsis-core#162]
Not a bug but a question:
I have files(<10MB) which are part of my model. Does Katharsis support multipart POSTs or some other way to support small files? Is there a design pattern I could use? I might encode files with base64 but that would be a problem for my client.

**Comment by meshuga** [comment]
Katharsis gives support for JSON API only. You should look in web framework of your choice on how to handle multiparts which should be used to pass binary files.
As a side note, if files are small enough (<1KB), I would just pass them in JSON requests in base64, but with bigger files there might be a problem with memory exhaustion.

**Comment by kkamkou** [comment]
Please, add this information to the general documentation.
