### ISSUE TITLE
Excluding static constants from serialization.

### ISSUE THREAD

**Issue by simmons** [katharsis-project/katharsis-core#163]
I have some constants in a model class (public static final String), and these are being included in the serialization of objects sent to the browser.  I don't see a way to avoid serializing statics, which is the common default behavior in many other tools that perform reflection (Java serialization, Jackson, Hibernate, etc.).  In fact, I don't see a way to suppress the inclusion of any field, static or otherwise.  (Even fields marked "transient" are included.)

It would be nice if there was a way to avoid including such fields, either by skipping statics, skipping transients, or using annotations.

**Comment by meshuga** [comment]
Thanks for the issue
`static` fields and methods and `transient` fields should be excluded.
