### ISSUE TITLE
KatharsisMatchingException messes up my mojo - context (info) needed 

### ISSUE THREAD

**Issue by ieugen** [katharsis-project/katharsis-core#170]
Hi, 

Working on building a vetx implementation for katharsis I finally got to something like this: 

````
        router.post("/:id/:field").handler(ctx -> {
            log.info("Update field");
            ctx.request().bodyHandler(requestBody -> {
                BaseResponse<?> response = null;
                boolean passToMethodMatcher = false;
                try {
                    response = katharsis.fieldResourcePost(ctx);
                } catch (KatharsisMatchingException e) {
                    log.error("Error {}", e);
                    passToMethodMatcher = true;
                } catch (Exception e1) {
                    throw Throwables.propagate(e1);
                } finally {
                    sendResponse(ctx, response, passToMethodMatcher);
                }
            });
        });
````

where the **fieldResourcePost** looks like: 

````
    public BaseResponse<?> fieldResourcePost(RoutingContext ctx) throws NoSuchMethodException,
        InstantiationException, IllegalAccessException, IOException, InvocationTargetException {
        Buffer body = ctx.getBody();
        try {
            JsonPath jsonPath = buildPath(ctx);
            QueryParams queryParams = createQueryParams(ctx);
            VertxParameterProvider parameterProvider = new VertxParameterProvider(objectMapper, ctx);
            return fieldResourcePost.handle(jsonPath, queryParams, parameterProvider, requestBody(body));
        } catch (KatharsisMappableException e) {
            return toErrorResponse(e);
        }
    }
````

What I like to achieve is to keep the Katharsis specific code as self contained as possible. But having the **KatharsisMatchingException** exception handling is not nice. 

My problem right now is that I don't really understand how I should handle it or how it should be handled. Could you provide a bit more context? What did you have in mind when you wrote the code like that? 

Could **KatharsisMatchingException** be integrated in the response somehow? like test for a failure condition:
````
 if ( response.failed()) {
   // handle KatharsisMatchingException 
} else {
  // return normal body to the client ?
}
````
In that case you might need to return a container that cand handle BaseResponse and/or the other Error. 

Thanks,

**Comment by ieugen** [comment]
I've noticed **ErrorResponse** . Is this reladed to/what I need?

**Comment by meshuga** [comment]
KatharsisMatchingException (as defined in Javadoc) indicates a matching error which disallows the request from further processing by Katharsis. It's intended for usage by adapters that might pass the request to other method matchers.

Thanks to that it might be possible to implement a method handling that has the same Content-Type and path as requests intended for Katharsis, but differs in some other cases and thus couldn't be processed successfully by Katharsis.
