### ISSUE TITLE
How to map to an array of Enum values?

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#174]
Glad to see the 2.x releases finally land!  We are building out around that using JPA under the covers to manage the actual data.  However, I've just run up against a mapping that I can't figure out how to really handle in Katharsis and/or JSON:API.  The JPA object has a number of attributes defined similarly to:

	@Enumerated(value = EnumType.STRING)
	@ElementCollection(targetClass = OrganizationOfficeTypeEnum.class)
	protected List<OrganizationOfficeTypeEnum> types;

Thus, I end up with a mapping from my Organization entity to a set of String values that don't have an id field.  I have a similar mapping that goes direct to String values:

	@ElementCollection
	protected List<String> roles;

Any suggestions on how to handle this in Katharsis/JSON:API?
Thanks!

**Comment by meshuga** [comment]
I think it should be just a plain attribute.

**Comment by csetera** [comment]
Thanks.  How would I handle a "list" of values as a plain attribute?

**Comment by meshuga** [comment]
Just don't add `JsonApiToMany` annotation :wink:

**Comment by csetera** [comment]
That would make too much sense :-)  I will give this a try.
