### ISSUE TITLE
Include Relationships

### ISSUE THREAD

**Issue by corrspt** [katharsis-project/katharsis-core#179]
I'm using Katharsis 2.0.0

I was experimenting with the `include relationship` feature (using the `@JsonApiLookupIncludeAutomatically` annotation) and from the documentation I found this example:

```
/tasks/?include[Task]=author
```

So I did just that and adapted it to my needs:
```
/pqrs/1/?include[Type]=typeRelation
```

And my Java class

```java
@JsonApiResource(type = "pqrs")
public class PQR {
   private  Long id;
   private Type type;
   @JsonApiToOne
   @JsonApiLookupIncludeAutomatically
   public Type getTypeRelation() {
    return type;
   }
   @JsonApiId
   public Long getId(){ return id;}
}

@JsonApiResource(type = "types")
public class Type {
   private String name;
   public String getName(){
    return name;
  }
}
```

If I do this exact request I get the following exception:

```
Caused by: java.lang.NullPointerException: null
	at io.katharsis.jackson.serializer.IncludedRelationshipExtractor.extractIncludedRelationships(IncludedRelationshipExtractor.java:105) ~[katharsis-core-2.0.0.jar:na]
	at io.katharsis.jackson.serializer.IncludedRelationshipExtractor.extractIncludedResources(IncludedRelationshipExtractor.java:39) ~[katharsis-core-2.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serializeSingle(BaseResponseSerializer.java:89) ~[katharsis-core-2.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.writeResponseWithResources(BaseResponseSerializer.java:69) ~[katharsis-core-2.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:37) ~[katharsis-core-2.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:15) ~[katharsis-core-2.0.0.jar:na]
```

*but* if I change my request to the following, it works:
```
/pqrs/1/?include[pqrs]=typeRelation
```

It makes sense, because in the `IncludedRelationshipExtractor` we have this:

```java
String elementName = response.getJsonPath()
            .getElementName();
        IncludedRelationsParams includedRelationsParams = findInclusions(includedRelations, elementName);

.....
private IncludedRelationsParams findInclusions(TypedParams<IncludedRelationsParams> queryParams,
                                                   String resourceName) {
        IncludedRelationsParams includedRelationsParams = null;
        if (queryParams != null && queryParams.getParams() != null) {
            for (Map.Entry<String, IncludedRelationsParams> entry : queryParams.getParams()
                .entrySet()) {
                if (resourceName.equals(entry.getKey())) {
                    includedRelationsParams = entry.getValue();
                }
            }
        }
        return includedRelationsParams;
    }
```

Where the `elementName` that is passed to the `findInclusions` method is `pqrs` (the resource being requested) and when it tried to match the `pqrs` with the `Type` (that was in the include field) it naturally fails...

So, am I doing something wrong here, or is it a bug? Do keep in mind that I'm using the playframework and I'm responsible for creating the QueryParams instance and what not.

Thanks!

**Comment by zachncst** [comment]
The @JsonApiLookupIncludeAutomatically annotation is based off of the field names. It's the same way relationships are displayed in the rest of Katharsis. This is how it's supposed to work because you could have more than one kind of relationship with the same type of class, albeit probably rare, it could happen.  The null pointer is a bug however, as it should fail more gracefully.

**Comment by meshuga** [comment]
NPE is always indicator of a bug :smiley:

**Comment by corrspt** [comment]
Thanks for pitching in, guys. @zachncst and @meshuga.

`This is how it's supposed to work because you could have more than one kind of relationship with the same type of class, albeit probably rare,` - Oh I need this, so no complaints there, eh eh

However I do have something that's puzzling me. My resource is "PQR" with the JSONAPI resource type being "pqrs" (plural) you're saying that I have to pass the plural as the resource type, always?

Another problem I found, I have a resource `MyProcess" which in JSONAPI becomes "my-processes" if I try to include do 
`/api/my-processes?include[my-processes]=relationName` 
Katharsis also fails, because when it compares the names it's comparing "my-processes" with "processes" it looses the "my" when doing the `findInclusions`

**Comment by zachncst** [comment]
I'm not quite sure why you're formatting your include that way. It should be:
/api/my-processes?include=['relationName']

Have you tried this format?

**Comment by corrspt** [comment]
Hey, so this is basically what happens
![npe_katharsis](https://cloud.githubusercontent.com/assets/789263/11496707/b8bfaeb2-980b-11e5-9343-0b1300039471.png)

I made a collage with the situation. I highlighted why the NPE happens when I try what you suggest.

**Comment by meshuga** [comment]
It should be `include[my-processes]=relationName`. I'll try to find out what's going on here, but probably not today.

**Comment by meshuga** [comment]
I fixed query params builder which stripped the resource types if there was a dash inside of it. After all, thanks for the issue!

**Comment by corrspt** [comment]
Thanks you very much @meshuga :+1: , can I expect a minor release with this fix?

**Comment by meshuga** [comment]
Yeah, tomorrow. I'll try to include some other fixes.

**Comment by corrspt** [comment]
Cool! Thanks :+1:
