### ISSUE TITLE
Strange behavior when using Jackson's @JsonProperty  

### ISSUE THREAD

**Issue by Mktmac** [katharsis-project/katharsis-core#184]
Hi guys,

We've found a strange issue when we're using Jackson's @JsonProperty on a POJO field to ensure dash-case for JsonAPI. Here is a small extract from our POJO:
``` java
class MyPojo {
   @JsonProperty("first-name")
   private String firstName;
}
```

The REST serialization of this small POJO ends up looking like:
``` javascript
{
    "data": {
        ...
        "attributes": {
            "firstName": "first name",
            "first-name": "first name"
        },
       ...
}
```
The objectMapper doesn't have any special configurations to it.

After doing some debug, the class `ContainerSerializer` seems to be responsible for this serialization. This seems to be related to the enhancement described in https://github.com/katharsis-project/katharsis-core/issues/107

Are there any pointers that you guys can help us with? Have we missed something? Also, can the dash-case be implemented in the above mentioned serializer in a foreseeable future?

Thank you!

Kind Regards,
Daniel

**Comment by corrspt** [comment]
I've been using dashed names for fields (Ember Data) with Katharsis without trouble, the only difference I see to your code is that I have the `@JsonProperty` annotation on my `getter` (I don't have the fields as I'm using a wrapper class around my original object).

**Comment by Mktmac** [comment]
We're using Lombok for our getters and setters. Nevertheless, I've also tried to annotate the getter but the same behavior happens.

**Comment by corrspt** [comment]
Sorry then, I tried :)

Your code snippet doesn't have the `@JsonApiResource(type = "TYPE_NAME")` on the class, (I assume you would get an error without it, so it probably is there).

**Comment by meshuga** [comment]
Hi, thanks for the issue.
I'll try to fix this.

**Comment by Mktmac** [comment]
Hi, thanks for the quick fix! Can you please tell me if this fix has been released and what version should I look for?

Thanks,
Daniel

**Comment by meshuga** [comment]
You should use version 2.1.1

**Comment by Mktmac** [comment]
Hi @meshuga,

I checked the fix but unfortunately it still doesn't work as expected :(

Looking through the code I discovered that in katharsis-core-2.1.1.jar the class `ResourceFieldWrapper` was not updated. Here is how it still looks in the .zip file:
``` java
package io.katharsis.resource.information;

import io.katharsis.resource.field.ResourceField;

public class ResourceFieldWrapper {
    private ResourceField resourceField;
    private boolean discarded;

    public ResourceFieldWrapper(ResourceField resourceField, boolean discarded) {
        this.resourceField = resourceField;
        this.discarded = discarded;
    }

    public ResourceField getResourceField() {
        return resourceField;
    }

    public boolean isDiscarded() {
        return discarded;
    }
}
```
Please note the missing `originalName` field.

Can you please make another release?

Thank you,
Daniel

**Comment by meshuga** [comment]
Today I'll make another release

**Comment by ieugen** [comment]
Thank you for the prompt response and action.
