### ISSUE TITLE
Add OSGi Manifest headers

### ISSUE THREAD

**Issue by choeflake** [katharsis-project/katharsis-core#186]
For using the Katharsis project in an OSGi environment, the manifests of the jar files should have OSGi headers.

**Comment by choeflake** [comment]
And the commits:
https://github.com/choeflake/katharsis-parent/commit/674f365dc1b5d06df31d4489b3fca70bfe750634
https://github.com/choeflake/katharsis-rs/commit/da87dadee51d4bc243c69d26c88f89819a87830e

The same has to be done on other Katharsis projects.

The reflection dependency is made optional.

**Comment by meshuga** [comment]
Thanks for the issue, but I think reflections will stay non-optional, because it adds complexity for new-comers to set-up sth. working with Katharsis. I've never worked with OSGi, but do you think it'll cause some problems?

**Comment by choeflake** [comment]
Thanks for adding the headers. I have added the OSGi import header for org.reflections optional. OSGi and org.reflections is not the best combination. First of all you need the servicemix build of org.reflections (https://github.com/apache/servicemix-bundles/tree/master/reflections-0.9.10). Next, scanning for classes will not work out of the box. You have to add the URL of the containing jar to the reflections config. Last but not least, org.reflections requires a chain of dependencies.
Since #101 users can work without the need for org.reflections. When it is optional users are allowed to choose...

**Comment by meshuga** [comment]
ok, reflections will be optional.
