### ISSUE TITLE
Provide custom QueryParamsBuilder

### ISSUE THREAD

**Issue by coderange** [katharsis-project/katharsis-core#209]
Hi,

I would like to discuss a kind of feature request.

Katharsis sometimes deviates from the the JSON API spec (sort parameters format, etc) and although I find the Katharsis convention more flexible and more consistent, the fact is, it's not standard. To alleviate this issue I'd like to suggest Katharsis should allow the library users to provide their own  QueryParamsBuilder to the KatharsisFilter/Servlet etc. In turn, the QueryParamsBuilder should allow overriding parts of the parsing for each of the components of RestrictedQueryParamsMembers.... let's say make QueryParamsBuilder an interface with methods for parsing filter/sort/group/page/fields/include and provide the current Katharsis parameter restrictions convention as the default parsing implementation. This way you allow the users who want to adhere to the JSON API specification override only those small parts of interest. For example, if I want to handle the sort parameters as per JSON API specification, I should be able to extends the Katharsis default implementation of QueryParamsBuilder and override one method ... let's say parseSortParameters to contribute to the QueryParams.

Could you advise me on potential side effects or gotchas. If I get some free time, I'll try to have a go at it.

Thanks,

Razvan

**Comment by meshuga** [comment]
Sounds good to me and I'm happy you want to contribute to the project!
There's only one thing. QueryParamsBuilder is initialized/used in katharsis-servlet, rs and spring, so it would be great if those changes could be made in all those projects.

**Comment by coderange** [comment]
Yes, I'm aware of servlet/rs/spring using it. When I'll implement it, I'll make all the required updates. Thanks !

**Comment by meshuga** [comment]
Everything's merged.
One more time, thanks for the support!

**Comment by coderange** [comment]
Awesome, thanks ! I'm looking to continue contributing when time allows ;)

**Comment by dustinstanley** [comment]
I was reviewing this change and I can't figure out a way to actually use a custom QueryParamsParser without modifying the code in KatharsisInvokerBuilder.  It seems that when creating the builder an instance of DefaultQueryParamsParser is always handed in to it.  Is there something I am missing here or is it expected that the source be modified in order to utilize a custom parser?

Thanks for your work on this project!

**Comment by dustinstanley** [comment]
You can disregard my previous comment, I figured out that you can pass your own QueryParamsBuilder into the KatharsisInvokerBuilder, so I am all good there.  However, even with a custom builder/parser it seems like a partial solution.  I created issue #373 to see if there is a way to make katharsis more compliant.
