### ISSUE TITLE
Wrapping of exceptions makes exception mapping harder

### ISSUE THREAD

**Issue by andy36** [katharsis-project/katharsis-core#215]
In:
https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/utils/PropertyUtils.java#L46-L47
three types of exceptions are just wrapped as RuntimeException.
I am trying to create an exception mapper for when input contains fields that are not on the resource (which results in NoSuchMethodException from https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/utils/PropertyUtils.java#L181 ) but I have to create an exception mapper for RuntimeException due to the wrapping.

**Comment by thereallisa** [comment]
:+1:
