### ISSUE TITLE
JsonApiIncludeByDefault vs lazy=true

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#220]
We are currently using Katharsis to generate output that is consumed by our Ember Data application.  After a lot of debugging and pulling my hair out, I finally figured out why Ember Data wasn't seeing my "included" data from the response.  The problem is that, as currently implemented in the RelationshipContainerSerializer, the data element in the relationship that refers to the included block of data won't be generated unless @JsonApiToMany is set lazy = false.  So, while the included data is there, the relationship data reference is not.

Is there a particular reason to require setting lazy to false when @JsonApiIncludeByDefault is specified?  It seems like include by default should imply that lazy is false as the references will need to be followed anyway.

**Comment by meshuga** [comment]
Ye, it should imply that if `@JsonApiIncludeByDefault` is set, `lazy` parameter of `@JsonApiToMany` should be overridden to `false`.

**Comment by csetera** [comment]
I can try to find time to do a pull request... unfortunately, we are a bit behind on our Katharsis version at the moment, so I'm not in a great position to work on this for a bit.

**Comment by soldierkam** [comment]
@meshuga The same should happen when request contains "include" param. Currently user receive included resources but does not have linkage.
