### ISSUE TITLE
Custom QueryParams

### ISSUE THREAD

**Issue by jbadeau** [katharsis-project/katharsis-core#237]
Hello,

I have seen that you provide the standard JSON API query params but is there a way to add custom params?

**Comment by keithdmoore** [comment]
I was under the impression that you could pass as in whatever you want.

**Comment by jbadeau** [comment]
I am not katharsis yet but from looking at the QueryParams class I dont see how I would be able to get my custom typed params  like: 

queryParams.getCusomParam1()
queryParams.getCusomParam2()

**Comment by keithdmoore** [comment]
Looks like you can't. I suppose you are free to use the others however you see fit though.  It's all a matter of your custom implementation.  What kind of custom params would you possibly want to add?

**Comment by meshuga** [comment]
Which Katharsis integration do you use? It's possible to use Spring/JAX-RS annotations to get query params from request in annotation-based repositories.

**Comment by keithdmoore** [comment]
I would be curious as to how to do that.

**Comment by meshuga** [comment]
In theory you can't do that. Of course you could create a custom `QueryParamsBuilder` and use it to create an instance of a class which inherits from `QueryParams`and then use it in repository methods, but for me, it's not a good way.
Take a look at http://katharsis.io/docs . I know it's not easily explained, but it's possible to pass custom request parameters to repository methods - of course only from annotation based ones. When you use just bare servlet integration you can add a parameter of type `ServletContext`, `HttpServletRequest` or `HttpServletResponse` to a repo method and Katharsis will take care of initializing this parameter with request utilities.
