### ISSUE TITLE
Method Override

### ISSUE THREAD

**Issue by jbadeau** [katharsis-project/katharsis-core#238]
Hello,

Do you plan to support something like:

X-HTTP-Method (Microsoft)
X-HTTP-Method-Override (Google/GData)
X-METHOD-OVERRIDE (IBM)

e.g. client sends a POST request to be handled by the GET controller.

This is common in enterprises that have restrictions on what verbs are allowed.

**Comment by keithdmoore** [comment]
I think you could possibly solve this by using a custom filter in your app and transform the request to whatever route you are trying to goto.   I wouldn't expect Kartharsis or json-api to solve this problem.

**Comment by jbadeau** [comment]
From looking at  the architecture docs it appears that the Resource and Relationship Repositories are the main interfaces resource APIs. The JSON API spec does a good job of providing standard parameters for sorting, paging and filtering but in many companies there are query parameters which are not directly related to the resources. Some examples are:

- domicle
- bookingCenter
- parnerId
- mandator

Sometimes one needs to send a custom filter object which must be passed to a downstream service. I would prefer to access these in the same way as the other query parameters. I have not though about how to do this but I could give it a try if your interested in pull requests?

**Comment by keithdmoore** [comment]
I am relatively new to both json-api and katharsis.  json-api and katharsis may not be for everyone.  I have seen some folks try to create a custom api and then try to use some of the katharsis classes under the covers to at least return a json-api response.  The project I am currently working on is a Jersey based JAX-RS implementation using Spring Boot.  So right now we have three ways of creating resources.  Kartharis-based resources are currently co-mingled with JAX-RS and Spring Rest based resources.  It's ok for now but we might try to take a similar approach as others have.  For us, about the only request that we might want to handle differently is authentication/authorization.  We could probably convert that to a json-api if we really wanted to.

**Comment by meshuga** [comment]
I don't think it's something Katharsis should take care of. There are ways with dealing with headers that change HTTP method e.g. http://stackoverflow.com/a/15368395 and it should be solved in underlying web framework you use.
Regarding additional query parameters, it's possible to acquire the request object from a repository class.

**Comment by keithdmoore** [comment]
@meshuga I agree with you.  That's a good idea with regards to injecting the request.  With Spring you could inject the request into the repo like this:

```java
private @Inject HttpServletRequest request;
```
