### ISSUE TITLE
Jackson JsonFormat seems to be ignored by Katharsis

### ISSUE THREAD

**Issue by keithdmoore** [katharsis-project/katharsis-core#240]
Are most of the Jackson annotations ignored on a model?  I am trying to do the following.   
```java
 @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    private Date birthDate;
```
I have set this in `application.properties`
```
spring.jackson.serialization.write_dates_as_timestamps=false
```
The output looks like this:
`"birthDate": "1958-04-09T00:00:00.000+0000"`
what I want is:
`"birthDate": "1958-04-09"`

The only way I was able to get it to work was to create my own ObjectMapper bean but that totally messes up the format of the entire JSON structure.  Otherwise, I would have to set it globally with:
```
spring.jackson.date-format=YYYY-MM-dd
```

**Comment by pcdwr** [comment]
I need this as well. I would like to be ale to set a default serialization for a type and override it at the property level.

**Comment by meshuga** [comment]
The thing is that for direct attributes serialization, Jackson isn't used. It can be changed. I just need to know a serialization method that accepts apart from field name and value, field annotations.

**Comment by meshuga** [comment]
I could use https://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/ser/impl/SimpleBeanPropertyFilter.FilterExceptFilter.html to exclude id and relationships fields and then in https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/jackson/serializer/ContainerSerializer.java#L147 pass the whole object, but there one thing - is it OK to add a filter for each resource? What in the case when a developer would use an ObjectMapper instance for with resource classes for other purposes?

**Comment by tdj-br** [comment]
I'm writing another solution that cover this case too. Let me send a PR in a few minutes.

**Comment by meshuga** [comment]
Great!

**Comment by meshuga** [comment]
Done in https://github.com/katharsis-project/katharsis-core/pull/241

**Comment by collinpeters** [comment]
I am using Spring and am wondering if this fix makes my workaround for using the Spring created ObjectMapper moot

```
public class CustomKatharsisInvokerBuilder extends KatharsisInvokerBuilder {

	@Inject
	private ObjectMapper springObjectMapper;

	protected ObjectMapper createObjectMapper(ResourceRegistry resourceRegistry) {
		// I want to use the Spring created Object mapper. So injecting it above, then registering the
		// Katharsis module and adding Java Time serialization support.

		// still use katharsis data binding
		springObjectMapper.registerModule(createDataBindingModule(resourceRegistry));
		// Java 8 Date/Time
		springObjectMapper.registerModule(new JavaTimeModule());

		return springObjectMapper;
	}
}
```

With this code I didn't have any problems with Java date formatting.
