### ISSUE TITLE
Inclusion of multiple relationships on same object is not working

### ISSUE THREAD

**Issue by collinpeters** [katharsis-project/katharsis-core#242]
Based on the docs, I am trying something similar to `GET /tasks/?include[tasks][]=author&include[tasks][]=comments`. I read this as "on the tasks response, include both the author and the comments". This doesn't seem to work for me. Ultimately when it gets to me the `IncludedRelationsParams` only contains the last include which is comments in this case.

I think there is a bug in QueryParams#setIncludedRelations. When I trace through this code, the `inclusions` method parameter contains `{include[tasks][]=[author, comments]}`. However, when it exits it sets `this.includedRelations` to something that only contains one `Inclusion` object which is comments. From what I can tell it isn't looping the passed in values, but rather just getting one. See line 328
```
resourceParams.add(new Inclusion(entry.getValue()
                    .iterator()
                    .next()));
```
Should this not loop the iterator and add multiple `Inclusion`s?

**Comment by meshuga** [comment]
Yes, it should be a list of inclusions.
