### ISSUE TITLE
Pojo fields are returned only if parent resource contains field with the same name

### ISSUE THREAD

**Issue by Sandmania** [katharsis-project/katharsis-core#246]
Tested with current jersey-example (2.3.0).

Steps to reproduce:
1. Create a new class called Pojo
2. Add instance variables String name, description. Initialise these as "pojoname" and "description"
3. Add instance variable Pojo to Project resource. Initialise it as new Pojo();
4. Modify ProjectRepository findOne to always return new Project();
5. Start example application
6. Call http://localhost:8080/projects/1

Expected result:
Project with pojo is returned, where both the name and description fields are present
```
{
  "data": {
    "type": "projects",
    "id": "null",
    "attributes": {
      "pojo": {
        "name": "pojoname",
        "description": "description"
      }
    },
    "relationships": {},
    "links": {
      "self": "http://localhost:8080/projects/null"
    }
  },
  "included": []
}
```

Actual result:
Pojo in Project is missing the description field

```
{
  "data": {
    "type": "projects",
    "id": "null",
    "attributes": {
      "pojo": {
        "name": "pojoname"
      }
    },
    "relationships": {},
    "links": {
      "self": "http://localhost:8080/projects/null"
    }
  },
  "included": []
}
```

**Comment by tdj-br** [comment]
I understood the problem.

In the ContainerSerializer.java (getObjectMapper method) we are adding a filter into object mapper (SimpleBeanPropertyFilter.filterOutAllExcept). 

This filter is being used recursively to the object.

I think that the way to fix this is creating a special filter that will handle the allowedFields information correctly (considering root attributes and non root attributes)

Unfortunately i will not have time to do it in next few days, but i can give you some help, if needed.

**Comment by Sandmania** [comment]
If you can give me a nudge to the right direction, I can give it a shot. Thou, I'm gonna start my week long winter vacation tomorrow, chances are that I don't wanna do that much coding :)

**Comment by keithdmoore** [comment]
Is this an issue that was introduced with the 2.3 release?

**Comment by Sandmania** [comment]
Not entirely sure. I was previously using 2.1.1 without this problem. I'll try to test this with 2.1.5 and 2.2.0 if I have the time.

**Comment by keithdmoore** [comment]
@Sandmania Ok. I don't recall having this problem with 2.2 using the Spring example.

**Comment by tdj-br** [comment]
@keithdmoore This behaviour was introduced with the change of attributes serializing.

The problem occours when you have an attribute that is an object. I didn't figured this issue because i always reference objects with the toOne annotation, so the "nested" objects are linked resources and not attributes.

Does anybody know if this type of attributes is compliant with JSONAPI and jsonapi clients?

**Comment by Sandmania** [comment]
"Complex data structures involving JSON objects and arrays are allowed as attribute values."

http://jsonapi.org/format/#document-resource-object-attributes

**Comment by tdj-br** [comment]
Good, so for these objects, we will like for "IncludeByDefault" annotations? Or this complex data structures will be rendered as a regular object, only looking for the jackson annotations?

**Comment by tdj-br** [comment]
I'm writing a fix considering that this inner objects will not support JsonApi annotations, only Jackson annotations.

**Comment by Sandmania** [comment]
Imho these should be always included by default.

**Comment by tdj-br** [comment]
Yes, because they are not resources, they are complex attributes...

**Comment by tdj-br** [comment]
Fixed, let's wait for merge.

**Comment by Sandmania** [comment]
Thanks! You should consider removing the system.out.printlns

**Comment by tdj-br** [comment]
Yeah I removed just after the first commit. Tks

**Comment by keithdmoore** [comment]
@tdj-br  All things considered, I think this is a reasonable approach.
