### ISSUE TITLE
Embeddable Id as JsonApiId

### ISSUE THREAD

**Issue by hnf1991** [katharsis-project/katharsis-core#251]
I am having a composite primary key and I am using it as EmbeddedId.
But when this id is returned to me from Katharsis Resource Repository it is like below:

`
{
  "data": {
    "type": "users",
    "id": "com.model.UserId@22b1aeae",
    "attributes": {
      "name": "aaa"
    }
}
`
How to handle this composite primary key behavior?

**Comment by meshuga** [comment]
Wow, when I was implementing resource identifier functionalities there was a requirement that it must be a String. Now there's no such requirement - http://jsonapi.org/format/#document-resource-identifier-objects

**Comment by hnf1991** [comment]
How can this behavior be handled now..?. toString implementation is ok for GET request but not with POST or PATCH.
Anything that can help me out for now..?

**Comment by hnf1991** [comment]
May be If repository or jsonmodel can provide the user to override the TypeParser for his Composite Ids so he can parse his Id the way he want.. But still lot of refactoring will be required for this

**Comment by meshuga** [comment]
You can always take this issue and implement it :wink: 
I can help you and write what do do.

**Comment by asadyarkhan007** [comment]
I am having the same issue. @meshuga you should have consider this case in your core API.

**Comment by szubtsovskiy** [comment]
@hnf1991 would it work if you changed your `UserId getId()` and `setId(UserId id)` to `String getId()` and `setId(String id)`? In this case you could serialize/deserialize your composite ID in the getter and setter and still have it working with JPA (or what you are using?) by annotating the field (not the method) with `@EmbeddedId`. JPA would set the value directly to the field and Katharsis would use getter and setter. This is what JavaBeans are for.

**Comment by hnf1991** [comment]
Yup. This is what we did :)
