### ISSUE TITLE
Possible Enhancement: Optional QueryParams argument with @JsonApiMeta

### ISSUE THREAD

**Issue by jps1982** [katharsis-project/katharsis-core#265]
I am trying to implement pagination and I have a "total-count" metadata field in my JSON:API messages similar to the example here: http://jsonapi.org/examples/#pagination

My current use case is:
```
@JsonApiFindAll
public Iterable<User> findAll(QueryParams queryParams) {
   //read the query params
   //query 1 page of user data
}
```

and 

```
@JsonApiMeta
public MetaInformation getMetaInformation(Iterable<User> resources) {
   //query the total count of users
}
```

This solution works fine when there are no filter parameters applied, but when using filtering, my query to get the total count of users also needs to take the filter parameters into consideration.

Is it possible for a future enhancement to add the QueryParams as an optional second argument?  Maybe even have another annotation?  What I really need to do is something like this:

```
@JsonApiMetaWithQueryParams
public MetaInformation getMetaInformation(Iterable<User> resources, QueryParams params) {
   //read the query params
   //query the total count of users
}
```

I'm not sure if there is a better way to do this.  Thanks!

**Comment by meshuga** [comment]
It should be possible to get `QueryParams` when using `@JsonApiMeta` annotated methods. Sth like this should do the job:
```java
@JsonApiMeta
public MetaInformation getMetaInformation(Iterable<User> resources, QueryParams params) {
   //query the total count of users
}
```

**Comment by jps1982** [comment]
Looks like that worked.  Thanks!

I was reading this enhancement and had another question along the same lines: https://github.com/katharsis-project/katharsis-core/issues/103

Is it possible to pass additional parameters in the 'delete' method as well?

Example:

> DELETE http://host.local/tasks/1?customparameter=test

```
@JsonApiDelete
public void delete(String id, @RequestParam("customparameter") String customParameter){
		
}
```

**Comment by meshuga** [comment]
yes, it is

**Comment by jps1982** [comment]
Cool.  Thanks again.

**Comment by meshuga** [comment]
No problem! :smile:
