### ISSUE TITLE
Support for dynamic resource attributes

### ISSUE THREAD

**Issue by robmartin0** [katharsis-project/katharsis-core#267]
It is often the case that we don't have a rigid schema for a resource and instead want many, if not all, of our attributes to be dynamic in nature, acting like a simple map. It would be extremely useful if we could use the @JsonAnyGetter/@JsonAnySetter annotations in our resources to achieve this. Furthermore support for the @JsonUnwraped would also be much appreciated.

**Comment by meshuga** [comment]
Looks like some good ideas!

**Comment by meshuga** [comment]
Thanks for the issue!
