### ISSUE TITLE
Filtering implementation versus documentation issues

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#274]
There appear to be some typos in the Katharsis filter docs.  I have done a quick look through latest code, and these issues appear to still be relevant.  

## Special Characters not Accepted  
Filter can be defined with special characters (to indicate an operation).  The example doc has:

`GET /tasks/?filter[tasks][name][$startWith]=Super task`

Looking at the implementation in QueryParams.buildPropertyListFromEntry, the following regular expression is used: "[\\w-]+(?<!\\[)(?=\\])".  From my experimentation with this, this will match words (\w), optionally with '-' separators, within brackets.  Unfortunately, \w will not match special characters like '$', as in the documentation.  The only special character allowed would be underscore.  So either the regular expression is wrong, or the documentation is wrong.  For our use cases, we would prefer to be able to use something other than underscore to indicate an operation if it is possible to update the regular expression.

## Multiple Filters 
Multiple filters are documented as follows:

`GET /tasks/?filter[tasks][name][][$startWith]=Super&[tasks][name][][$endWith]=task`

From stepping through code, this appears to be incorrect.  A secondary filter criteria would need to start with 'filter'.  In short, the correct documentation would be:

`GET /tasks/?filter[tasks][name][][$startWith]=Super&filter[tasks][name][][$endWith]=task`

This appears to be purely as documentation error, as the query parameters will always be split on the ampersand.

**Comment by meshuga** [comment]
You were right. Thanks for the issue!
