### ISSUE TITLE
Comma delimited query string parameter value

### ISSUE THREAD

**Issue by pcdwr** [katharsis-project/katharsis-core#278]
As a caller I would like to be able to pass a comma delimited set of values for a query parameter.

In the current version the DefaultQueryParamsParser returns a map - ` Map<String, Set<String>> `  however there is only one entry in the set for a given key even if a comma delimited value is passed for the parameter.

Currently to request a sparse fieldset of more than one field the following query parameters are required:

fields[users]=abc&fields[users]=def

If comma delimited values were supported the parameter could be passed as follows:

fields[users]=abc,def

**Comment by meshuga** [comment]
You can implement your own `QueryParamsParser` to split passed query value into a set of values. Take a look at the example below:

```java
public class CommaDelimitedQueryParamsParser implements QueryParamsParser {

    @Override
    public Map<String, Set<String>> parseIncludedFieldsParameters(final Map<String, Set<String>> queryParams) {
        String sparseKey = RestrictedQueryParamsMembers.fields.name();
        return filterQueryParamsByKey(queryParams, sparseKey);
    }

    // ...

    private static Map<String, Set<String>> filterQueryParamsByKey(Map<String, Set<String>> queryParams, String queryKey) {
        Map<String, Set<String>> filteredQueryParams = new HashMap<>();

        for (Map.Entry<String, Set<String>> entry : queryParams.entrySet()) {
            if (entry.getKey().startsWith(queryKey)) {
                Set<String> commaSeparatedValues = entry.getValue();
                Set<String> splittedValues = new HashSet<>();
                for (String commaSeparatedValue : commaSeparatedValues) {
                    splittedValues.addAll(Arrays.asList(commaSeparatedValue.split(",")));
                }
                filteredQueryParams.put(entry.getKey(), splittedValues);
            }
        }
        return filteredQueryParams;
    }
}
```

The created parser can be passed to Katharsis by any adapter e.g. here: https://github.com/katharsis-project/katharsis-examples/blob/master/jersey-example/src/main/java/io/katharsis/example/jersey/KatharsisDynamicFeature.java#L16

**Comment by pcdwr** [comment]
Thanks for the example this worked well for the comma delimited parser.

**Comment by meshuga** [comment]
Great! I'll include this class in katharsis-core and write some docs.
