### ISSUE TITLE
Upgrade jackson version to 2.7.x

### ISSUE THREAD

**Issue by danielmischler** [katharsis-project/katharsis-core#280]
With Dropwizard nearing 1.0 that's including jackson 2.7.3 it would be great to have katharsis moving along. This would make the new PropertyNamingStrategy KEBAB_CASE available.

**Comment by meshuga** [comment]
Ok, newest Wildfly will probably upgrade to 2.7.1, current spring version also use 2.7.1, so it might be a good idea to move forward.

**Comment by ieugen** [comment]
I would do the version migration as a new minor release.
Also if there katharsis does not ue any of the jackson 2.7.x API's directly then there is _no reason_ to upgrade. Use the lowest version an let clients decide which one they use. It's common best practice in scenarios like this.

**Comment by olabomba** [comment]
Annotated.construct signature has changed in Jackson 2.7, so the code "AnnotatedClass.construct(field.getDeclaringClass(), aintr, serializationConfig)" (from ResourceFieldNameTransformer class) isn't compatible anymore when we want to use a SerializationConfig.

So, we can't use the new KEBAB_CASE strategy...

**Comment by meshuga** [comment]
Both of what @ieugen and @olabomba is important, so to allow the users to use Jackson 2.7+ and lower versions I'll refactor the code to find out which Jackson version is available and then use proper `com.fasterxml.jackson.databind.introspect.AnnotatedClass#construct` method.

**Comment by meshuga** [comment]
Now it's possible :wink:
I'll obligate myself to make a new release (2.3.2) at the end of this week
