### ISSUE TITLE
Inject QueryParams class

### ISSUE THREAD

**Issue by pcdwr** [katharsis-project/katharsis-core#283]
Would  you look at converting the QueryParams class to an interface and allowing it to be injected? I have a use case for some custom query params and I would like to store them as TypedParams.

**Comment by meshuga** [comment]
I think it might be better to implement own `io.katharsis.queryParams.QueryParamsBuilder` and make the builder method return a class that inherits from `QueryParams`.

**Comment by pcdwr** [comment]
All the setters in QueryParams are private so I effectively have to recreate the whole class even if I inherit from the base class. I guess that is the same as injecting my own. Any chance you could make the setters public so I can extend the class and just add the custom QueryPrams? I just saw https://github.com/katharsis-project/katharsis-core/issues/237 <https://github.com/katharsis-project/katharsis-core/issues/237> and it looks like this has been discussed before. I think I will just process them myself as suggested by https://github.com/meshuga <https://github.com/meshuga>.
