### ISSUE TITLE
OPTIONS request

### ISSUE THREAD

**Issue by pcdwr** [katharsis-project/katharsis-core#284]
Could you look at adding a ResourceOptions controller? I wrote my own but I had to override several Katharsis classes and inject my own RequestDisptacher. It would be nice if I could just annotate a function in the ResourceRepository to handle the OPTIONS call. Thanks again for you help. I really enjoy using Katharsis.

**Comment by meshuga** [comment]
But you can create a list of base Katharsis controllers from `DefaultControllerLookup#getControllers` method, add custom ones and then pass the list to new instance of `ControllerRegistry`. It's pretty straightforward way.

**Comment by pcdwr** [comment]
That works. Thanks.

**Comment by pcdwr** [comment]
Good solution. Thanks.
