### ISSUE TITLE
Compatibility with Spring Security - EnableGlobalMethodSecurity

### ISSUE THREAD

**Issue by olabomba** [katharsis-project/katharsis-core#290]
Hello,
I do not know if it is clean to my setup but impossible to operate a repository Katharsis with methods annotated via Secured or PreAuthorize.
I always get the following error:

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.aopalliance.intercept.MethodInterceptor]: Factory method 'methodSecurityInterceptor' Threw exception; nested exception is org.springframework.security.config.annotation.AlreadyBuiltException: This Object has already-been built 
`

Do you have an idea ?
Thanks

**Comment by meshuga** [comment]
It's similar to the thing I've encountered and described in https://github.com/katharsis-project/katharsis-core/issues/217#issuecomment-181563947. The repository instances are created at the initialization time.

**Comment by meshuga** [comment]
Could you pastę a gist so I could take a look at It?
