### ISSUE TITLE
Wrong relationships url

### ISSUE THREAD

**Issue by yannissgarra** [katharsis-project/katharsis-core#296]
Hi !
These are my two entities : 

    @JsonApiResource(type = "languages")
    class Language {

        @OneToMany(mappedBy = "language")
        @JsonApiToMany
        Set<SiteUrl> siteUrls
    }

    @JsonApiResource(type = "site-urls")
    class SiteUrl {

        @ManyToOne
        @JoinColumn(name = "language_id")
        @JsonApiToOne
        Language language
    }

But, when I read JSON from `/api/languages/1`, defined relationships are : 

    "relationships": {
      "siteUrls": {
        "links": {
          "self": "http://localhost:8081/api/languages/1/relationships/siteUrls",
          "related": "http://localhost:8081/api/languages/1/siteUrls"
        }
      }
    }

I think Camelcased "siteUrls" must be kebabcased site-urls (like in my entity definition (in `@JsonApiResource`)) : 

    "relationships": {
      "site-urls": {
        "links": {
          "self": "http://localhost:8081/api/languages/1/relationships/site-urls",
          "related": "http://localhost:8081/api/languages/1/site-urls"
        }
      }
    }

What do you think ?
Thanks ! :)

**Comment by meshuga** [comment]
It's not a bug, you just defined a to-many relationship of **type** `site-urls` with a name `siteUrls`. Imagine a more extended case i.e.
```java
@JsonApiResource(type = "languages")
class Language {

    @OneToMany(mappedBy = "language")
    @JsonApiToMany
    Set<SiteUrl> administrationUrls

    @OneToMany(mappedBy = "language")
    @JsonApiToMany
    Set<SiteUrl> visitorUrls
}
```

**Comment by yannissgarra** [comment]
Hi!

Ok, but I've defined KEBAB_CASE for Jackson : `spring.jackson.property-naming-strategy: KEBAB_CASE` and it works like a charm for "classic" fields (since your last correction about that), but not for "relationship" fields which stay in CamelCase.

So, I think there is a bug.

**Comment by yannissgarra** [comment]
Moreover, as I've defined `KEBAB_CASE`, I can see nested relationships inside JSON `data.attributes`, under kebab_case format element, and relationships in CamelCase, i.e.

    {
      "data": [{
          "type": "languages",
          "id": "1",
          "attributes": {
              "name": "English",
              "site-urls": [{
                  "id": 1,
                  "domain": "www.example1.com"
              }]
          },
          "relationships": {
              "siteUrls": {
                  "links": {
                      "self": "http://localhost:8081/api/languages/1/relationships/siteUrls",
                      "related": "http://localhost:8081/api/languages/1/siteUrls"
                  }
              }
          }
      }]
  }

But when I force `KEBAB_CASE`, by using `@JsonProperty("site-urls")` on my "relationship" field, I get a correct JSON, i.e.

    {
      "data": [{
          "type": "languages",
          "id": "1",
          "attributes": {
              "name": "English"
          },
          "relationships": {
              "site-urls": {
                  "links": {
                      "self": "http://localhost:8081/api/languages/1/relationships/site-urls",
                      "related": "http://localhost:8081/api/languages/1/site-urls"
                  }
              }
          }
      }]
  }

**Comment by meshuga** [comment]
Oh, yes, it's an inconsistency. Relationship names should respect Jackson property naming strategy.

**Comment by yannissgarra** [comment]
Yes, I work with @olabomba but we don't understand how to fix our problem, because we defined `KEBAB_CASE`, and it works for class attributes but web still have relationships fields in CamelCase...

**Comment by meshuga** [comment]
I could help you, but I'm still having problems with getting katharsis-spring tests working correctly after applying katharsis-project/katharsis-spring#25 fix.

Could you take a look at them (https://github.com/katharsis-project/katharsis-spring/blob/development/src/test/java/io/katharsis/spring/boot/SpringBootSimpleExampleApplicationTests.java) and help me make them working?

**Comment by olabomba** [comment]
Hi,
I've cloned katharsis-spring in my eclipse environment (with maven M2e).
Without any modification, the tests are working well.

I wanted to test the changes introduced in #25. So, I've added a "firstName" field to the Task entity (John / Malkovitch, with a modification on the assertion).

I've added jackson-databind in 2.7.3 in the pom.xml.

I've printed the output of the json in the test, and without modifying Jackson properties, I've got the field printed like this : "firstName".

Then, I added to the test application.properties the line : "spring.jackson.property-naming-strategy: KEBAB_CASE".

The field is now printed like this "first-name".

I have not encountered any errors during all these steps, and operation is the one expected "for the fields"; can you tell me what does not work for you at this stage?

Now it would be cool if relations could benefit from this Jackson property (is there another ObjectMapper configuration?)

Thank you for your attention to this matter.
