### ISSUE TITLE
Does Katharsis support Relationship attribute in Create resource API?

### ISSUE THREAD

**Issue by kaleeswaran393** [katharsis-project/katharsis-core#313]
Hi Team,
      As per the jsonapi standard we can pass the child object with relationship but when i tried using Katharsis implementation its not support relationship attribute,

below is the sample create reasource i got it from jsonapi site,  but when i post request with relationship the request binding is not happening, but if i remove relationship request binding is happing with resource object but child object is not created.

POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    **"relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }**
  }
}

Please help me

**Comment by meshuga** [comment]
The sample above describes a request to create a new resource and add a new relationship between the newly created object and a persisted object from a repository. AFAIK it's supported.
