### ISSUE TITLE
Katharsis RESOURCE_SEARCH_PACKAGE is not loading the resources

### ISSUE THREAD

**Issue by kaleeswaran393** [katharsis-project/katharsis-core#314]
Hi Team,

Katharsis RESOURCE_SEARCH_PACKAGE is not loading the resources if the resource classes in another jar. its working find if the resources in the same project where the Katharsis repository and features present.

context.property(KatharsisProperties.RESOURCE_SEARCH_PACKAGE, "com.resources.domain");

this com.resources.domain package is in another jar and i have added as dependency.

Please provide your input, thanks!

**Comment by kaleeswaran393** [comment]
Any update on this issue?

**Comment by meshuga** [comment]
Are you using katharsis-rs, katharsis-servlet or katharsis-spring? We're using reflections library (https://github.com/ronmamo/reflections) and it doesn't work well with Wildfly and when resources are located in separate JAR.

**Comment by meshuga** [comment]
You can create a class which will implement `io.katharsis.resource.registry.ResourceLookup` interface like in https://github.com/katharsis-project/katharsis-core/blob/development/src/main/java/io/katharsis/resource/registry/DefaultResourceLookup.java and modify `io.katharsis.rsKatharsisFeature#createResourceLookup(FeatureContext)` to pass your class in case of using katharsis-rx integration..

**Comment by kaleeswaran393** [comment]
Its resolved. so closing
