### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by ashishgodani** [katharsis-project/katharsis-core#316]
I there an easy way to validate whether the mandatory params for a given resource at a GET request are present in the request path variables ?

Basically if I have a resource projects at http://localhost:8080/projects/123123 then how do I validate if 123123 is present in the path variable and its gracefully handled ?

**Comment by meshuga** [comment]
https://github.com/katharsis-project/katharsis-core/issues/314#issuecomment-220065016
Data validation is out of scope of Katharsis, although it's fairly easy to use Hibernate validation, especially with spring integration.
For next questions, please use our mail communication channel https://gitter.im/katharsis-project/katharsis-core

**Comment by ashishgodani** [comment]
So how would you do if you are not using an ORM framework ? Also, if 123123 is not present in the path it wont even reach hibernate and error out in spring mapping with Mapping not found for the resource.

Any pointers in this regard would be helpful.

**Comment by meshuga** [comment]
Sorry, path data validation is handled by Katharsis, so if you pass a GET request without an `id` e.g. `http://localhost:8080/projects/`, the request will be treated as a request for listing resources (according to http://jsonapi.org/format/#fetching-resources)

**Comment by ieugen** [comment]
@ashishgodani Hibernate Validation is a different thing from Hibernate ORM (they implement different standards)
