### ISSUE TITLE
Problems with upsert when JSON contains embedded classes

### ISSUE THREAD

**Issue by pcdwr** [katharsis-project/katharsis-core#323]
If the input JSON for a PATCH contains an embedded class (see example JSON below with embedded address) the upsert does not work as expected when there are missing or read-only fields (marked read-only with Jackson annotation). The issue occurs in ResourceAttributesBridge.setProperties. The property on the resource is completely overwritten with the input from the incoming JSON. If a property is missing from the input or it is marked as read-only it is set to null in the instanceWithNewFields object. Since the object is copied in it's entirety instead of walking the attributes, any existing values from the findOne are overwritten with null. 

In the example below if you patch and only include address.street the city and state will be set to null.

`"data": {
    "type": "customers",
    "id": "16745",
    "attributes": {
      "lastName": "ROBINSON",
      "email": "robinson@gmail.com",
      "address": {
          "street": "abc main street",
          "city": "Chicago",
          "state": "Illinois"
      }
    },`

**Comment by pcdwr** [comment]
I just realized this is basically the same issue as #319. I apologize for the duplication.

**Comment by meshuga** [comment]
I don't think it's a duplication. Yes, the input is overwritten. As for now we don't support handling of read only attributes (nested or not) like presented here https://gist.github.com/thurloat/2510887.

**Comment by weaselmetal** [comment]
Because @pcdwr mentioned read only properties, there is also this jackson bug:
https://github.com/FasterXML/jackson-databind/issues/935

Just in case `@JsonProperty(access = Access.READ_ONLY)` was used.

**Comment by keithdmoore** [comment]
My problem is similar, I just want the upsert to preserve any of the complex objects attributes.  For example, let's say I have a Task that looks like this:

```
{
  "data": {
    "type": "tasks",
    "id": "1",
    "attributes": {
      "address": {
        "street1": "street1",
        "street2": "street2"
      },
      "my-name": "Create tasks",
      "description": "desc"
    }
  } 
}
```

And I want to send a PATCH to update just street1:
```
PATCH /api/tasks/1 HTTP/1.1
Host: localhost:8080
{
  "data":{ 
    "type": "tasks",
    "id": "1",
    "attributes": {
      "address": {
        "street1": "street1 is updated and thats it"
      }
    }
  }       
}
```

Notice the response indicates `street2` has been set to null.  Seems like it should have overlaid `street2` with the value returned from the findOne.  
```
{
  "data": {
    "type": "tasks",
    "id": "1",
    "attributes": {
      "address": {
        "street1": "street1 is updated and thats it",
        "street2": null
      },
      "my-name": "Create tasks",
      "description": "desc"
    },
<truncated for brevity>
```

**Comment by pcdwr** [comment]
See pull request #340.
