### ISSUE TITLE
Http Caching - HTTP 304

### ISSUE THREAD

**Issue by arempala** [katharsis-project/katharsis-core#332]
I'd like to add Http Caching to my app. The plan is to include **_Last-Modified_** header in the response. If clients choose to send **_If-Modified-Since_** request header, and the resource has not changed since that time, I'd like to return HTTP 304. I'll actually need that on the To-Many relationship resource. My Repo is returning JsonApiResponse.

I might have opened it on the wrong project. I'm using katharsis-spring.

http://docs.spring.io/spring/docs/4.0.x/spring-framework-reference/html/mvc.html#mvc-ann-lastmodified doesn't work.

How do I go about it?

Seems like I can pass HttpServletRequest to my repo methods, and then I'd return KatharsisMappableException with httpStatus of 304? is that the right approach?

**Comment by meshuga** [comment]
Yes, throwing an exception can be a good approach, but if you want to do it in a more efficient way, you could also create a filter which will be executed before Katharsis and inside of it check caching headers.

**Comment by arempala** [comment]
That solves the case where I want to return HTTP 304. What about setting 'Last-Modified' response header on HTTP 200? 

My repos already return last-modified timestamp when fetching resources, so I'd like to set the 'Last-Modified' after Katharsis filter. However, Katharsis doesn't call chain.doFilter unless an exception is thrown...

Seems like I'd have to make to calls to the DB. One to get the time stamp form the pre-Katharsis filter, and another one to get the resource.
