### ISSUE TITLE
Documentation Support

### ISSUE THREAD

**Issue by PriyaKanna** [katharsis-project/katharsis-core#334]
I am trying to construct JsonAPIResponse format using KatharsisFieldPropertyFilter. any sample code or docs is highly appreciated?

**Comment by ieugen** [comment]
Hi, 

We have started writing documentation about this library [1]. You should check there in the future or add examples if you found a solution. 

I am closing this issue since it is too generic 

[1] http://katharsis-jsonapi.readthedocs.io/en/latest/
