### ISSUE TITLE
HMAC Security

### ISSUE THREAD

**Issue by ForresGeek** [katharsis-project/katharsis-core#341]
Hi all,

 I'm new to jsonAPI, but i've been working with Katharsis for the past two weeks, and slowly making progress.

 I'm using spring-boot & hibernate, and I've (nearly) got my API working the way I want.

Question / Advice please..
  
What would be a good approach to securing this API ?  

My client is keen to use some kind of HMAC rather than TLS. Using Katharsis, I feel I'm too far away from the raw HTTP request to be able to access header & implement a HMAC algorithm.

As I'm  already using spring-boot, would spring-security be a possible solution ?

Thanks in advance.

--
 Lee

**Comment by ieugen** [comment]
You could implement it as a filter, before the request reaches katharsis. This is how you would approach authentication. 

Intercept the request in your web framework, extract the Auth parameters, do Auth and if ok delegate to katharsis, otherwise respond with 401.
