### ISSUE TITLE
GZIP responses?

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-core#343]
Is it possible to automatically GZIP responses in Katharsis?  Is there anything inherent in JSON:API that would make that not possible?

**Comment by ieugen** [comment]
Hi @csetera ,

Compression is not the responsability of Katharsis. You can enable it in your HTTP framework. It is dependent on your HTTP framework. If you deploy behind a proxy (nginx, apache) you could enable compression there. 

[1] http://vertx.io/docs/vertx-core/java/#_http_compression
[2] http://tutorials.jenkov.com/java-servlets/gzip-servlet-filter.html
