### ISSUE TITLE
Add support for Jackson annotations

### ISSUE THREAD

**Issue by meshuga** [katharsis-project/katharsis-core#35]
Currently Jackson annotations assigned to resource and resource's fields aren't used. ~~It should be available by replacing current serializers and creating custom proxy classes (e.g. using javassist) which will contain fields from resources.~~
At this state, Javassist excesses the needs; only JsonProperty annotation should be supported.

**Comment by JliptonRTR** [comment]
Any way we can get support for JsonUnwrapped?
