### ISSUE TITLE
RelationshipRepository lookup breaks for relations of same type

### ISSUE THREAD

**Issue by weaselmetal** [katharsis-project/katharsis-core#360]
Assume this object being exposed on an API

    @JsonApiResource(type = "person")
    public class Person
    {
        private static long dumbIdGen = 1;

        private String name;

        private Long id;

        private Set<Person> parents = new HashSet<>();

        private Set<Person> children = new HashSet<>();

        public Person(String name)
        {
            id = dumbIdGen++;
            this.name = name;
        }

        @JsonApiId
        public Long getId()
        {
            return id;
        }

        public String getName()
        {
            return name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        @JsonApiToMany
        public Set<Person> getParents()
        {
            return parents;
        }

        public void setParents(Set<Person> parents)
        {
            this.parents = parents;
        }

        @JsonApiToMany
        public Set<Person> getChildren()
        {
            return children;
        }

        public void setChildren(Set<Person> children)
        {
            this.children = children;
        }
    }

Retrieving this object by id would correctly deliver this json response:

    {
      "data":{
        "type":"person",
        "id":"1",
        "attributes":{
          "name":"Bob"
        },
        "relationships":{
          "children":{
            "links":{
              "self":"http://localhost:8080/api/v2/person/1/relationships/children",
              "related":"http://localhost:8080/api/v2/person/1/children"
            }
          },
          "parents":{
            "links":{
              "self":"http://localhost:8080/api/v2/person/1/relationships/parents",
              "related":"http://localhost:8080/api/v2/person/1/parents"
            }
          }
        },
        "links":{
          "self":"http://localhost:8080/api/v2/person/1"
        }
      },
      "included":[

      ]
    }

However, since katharsis uses the type parameters to find a `RelationshipRepository` it cannot resolve the parents and children relation correctly. katharsis would just pick the first repository that matches and use it. The net effect is that I will always receive children, even if I want the parents.

Just for the sake of completeness, here are the RelationshipRepositories that cannot be differed by katharsis:

    @Component
    public class PersonToChildrenRelationshipEndpoint
            implements RelationshipRepository<Person, Long, Person, Long>
    {
        @Override
        public void setRelation(Person source, Long targetId, String fieldName)
        {
        }

        @Override
        public void setRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public void addRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public void removeRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public Person findOneTarget(Long sourceId, String fieldName, QueryParams queryParams)
        {
            return null;
        }

        @Override
        public Iterable<Person> findManyTargets(Long sourceId, String fieldName,
                QueryParams queryParams)
        {
            return Arrays.asList(new Person[] { new Person("Casey"), new Person("Cate") });
        }
    }

and

    @Component
    public class PersonToParentsRelationshipEndpoint
            implements RelationshipRepository<Person, Long, Person, Long>
    {
        @Override
        public void setRelation(Person source, Long targetId, String fieldName)
        {
        }

        @Override
        public void setRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public void addRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public void removeRelations(Person source, Iterable<Long> targetIds, String fieldName)
        {
        }

        @Override
        public Person findOneTarget(Long sourceId, String fieldName, QueryParams queryParams)
        {
            return null;
        }

        @Override
        public Iterable<Person> findManyTargets(Long sourceId, String fieldName,
                QueryParams queryParams)
        {
            return Arrays.asList(new Person[] { new Person("Alan"), new Person("Anne") });
        }
    }

I would always get Casey and Cate as both children and parents, which cannot be.
That would mean that this kind of type based lookup cannot work for the Person object. Maybe a URL based lookup is required.

**Comment by Ramblurr** [comment]
This is a pretty serious limitation of Katharsis :\

**Comment by chb0github** [comment]
We had a discussion on having a near term release; there is a lot outstanding and we are working to improve the regularity and repeatability of the process. If you supply a PR and we accept I will make getting a release out a priority discussion in our next hangout on wed. 

Does that help?

**Comment by chb0github** [comment]
BTW: This may be address by #356

**Comment by weaselmetal** [comment]
Doesn't seem like issue #356 is about the same thing.

**Comment by Ramblurr** [comment]
#356 isn't related as far as I can tell.

The cause of this seems to be that Katharsis is resolving relationships via the java type. If a resource has > 1 relationships with the same type (e.g., a Person with parents, and children, and friends), Katharsis can't distinguish between the relationships because its referring to the relationship via the Person type.

**Comment by chabala** [comment]
I'd say this is not a bug, those relationship repos are just highly naïve.

Look at https://github.com/katharsis-project/katharsis-examples/blob/master/dropwizard-mongo-example/src/main/java/io/katharsis/example/dropwizard/domain/repository/TaskToProjectRepository.java

The lookups make full use of the fieldName param to disambiguate relationships of the same type.

**Comment by weaselmetal** [comment]
Oooooooooo, so I'd need to check on the `fieldName` parameter whether the current relation deals with `parents` or `children`? Is that correct?

**Comment by Ramblurr** [comment]
Yea, I just tested this and the fieldName parameter is set to the target field of the type represented by the class. So parents or children in this case.

**Comment by weaselmetal** [comment]
Thanks @chabala for clearing this up and linking to code that uses `fieldName`. Closing the issue.
