### ISSUE TITLE
java 1.7 support

### ISSUE THREAD

**Issue by jbadeau** [katharsis-project/katharsis-core#48]
Do you plan to support java 1.7?

**Comment by meshuga** [comment]
Java 1.7 reached its end of public updates (http://www.oracle.com/technetwork/java/eol-135779.html), so we won't support it.

**Comment by datagitlies** [comment]
Using [retrolambda](https://github.com/orfjackal/retrolambda) and [streamsupport](http://sourceforge.net/projects/streamsupport/) I was able to backport katharsis-core to run on Java 7 @jbadeau you can see the result in our fork here https://github.com/StateFarmIns/katharsis-core/

**Comment by jbadeau** [comment]
Wow that's awesome. I am working in a big bank and they are always behind. I wok have a look next week

**Comment by meshuga** [comment]
The thing is that streamsupport doesn't have OSGi definitions, in fact it doesn't have even a manifest file. I've created an issue about that (http://sourceforge.net/p/streamsupport/tickets/143/) and as soon as this issue will be solved, I'll merge Java 7 support.

**Comment by datagitlies** [comment]
@meshuga thank you for reopening this issue and giving it serious consideration. @rbarbey this may be of interest to you.

**Comment by rbarbey** [comment]
@datagitlies Thank you for notifying me about this issue. I didn't use streamsupport or lambdaj, only plain Java 7 stuff. I'm stuck with slightly different type erasures for the methods in implementations of `BaseController`. But it seems that you have solved this already.

@meshuga If you have concerns about streamsupport and OSGi then maybe we could merge @datagitlies and my attempt to have Java 7 support. Would that be an option?

**Comment by meshuga** [comment]
Take a look here: https://github.com/katharsis-project/katharsis-core/pull/198

**Comment by datagitlies** [comment]
I'm thrilled @meshuga! I prefer the pure Java approach over using streamsupport and retrolambda. I only went down that path so that our fork would have minimal code changes and I could merge with confidence & ease. I'm anxiously awaiting approval of the pull request. FYI, you'll also have some slight changes to make in katharsis-rs, katharsis-servlet, and katharsis-spring. Mainly, to account for the removal of the default method `getParameter` in the `RepositoryMethodParameterProvider` interface from katharsis-core.

**Comment by meshuga** [comment]
Yeah, Parameter type was added in Java 8, so I had to do it.

**Comment by meshuga** [comment]
v2.1.3 requires Java 7 :+1:

**Comment by rbarbey** [comment]
:clap: :tada: Thank you very much for your effort!

**Comment by datagitlies** [comment]
ditto!

**Comment by jbadeau** [comment]
Awesome, very much appreciated 💪🏽🖐
