### ISSUE TITLE
Define complex data attributes

### ISSUE THREAD

**Issue by marrrschine** [katharsis-project/katharsis-core#57]
Is it possible to declare complex data structures (JSON objects) and arrays as attribute values for resource types / models? If so could you please give me an example?
(see http://jsonapi.org/format/#document-resource-object-attributes)

Thanks a lot!

**Comment by meshuga** [comment]
All of the values in the fields are passed directly to Jackson. You can take a look at the example https://github.com/katharsis-project/katharsis-examples/blob/master/wildfly-example/src/main/java/io/katharsis/example/wildfly/model/User.java#L27.
I know that's not so complex structure, just a list of strings, but in a similar manner you can put your own objects and even add custom (de)serializers ho handle more custom cases.
