### ISSUE TITLE
How to add a custom data store

### ISSUE THREAD

**Issue by nevson** [katharsis-project/katharsis-core#58]
Hi, currently I'm trying to add a custom data store to the [jersey-example](https://github.com/katharsis-project/katharsis-examples/tree/master/jersey-example). I've tried to get some inspiration from the dropwizard-mongo-example but somehow I felt a bit lost when having a look on the [DropwizardService.java](https://github.com/katharsis-project/katharsis-examples/blob/master/dropwizard-mongo-example/src/main/java/io/katharsis/example/dropwizard/DropwizardService.java).

In the end what I want to achieve is the following:
```java
public class TaskRepository implements ResourceRepository<Task, ObjectId> {
    private MyDatastore datastore;

    @Inject
    public TaskRepository(MyDatastoreManager manager) {
        datastore = manager.getDatastore();
    }
    // ...
}
```

Could you give me some guidance how I can achieve that based on the `jersey-example`? That would be really awesome!

**Comment by meshuga** [comment]
That's relatively simple. dropwizard-mongo-example uses Guice to provide DI. So, if you want to use it, there's lots you can find about it on the web e.g. on the dropwizard-guice bundle github page - https://github.com/HubSpot/dropwizard-guice.

But of course you can use any DI you want like Weld (https://github.com/katharsis-project/katharsis-examples/blob/master/wildfly-example/src/main/java/io/katharsis/example/wildfly/serviceLocator/WildflyServiceLocator.java), Spring CDI, HK2, or not use it at all. The only thing you need is to implement `JsonServiceLocator`. Take a look at the implementation of `SampleJsonServiceLocator`.
```java
public class SampleJsonServiceLocator implements JsonServiceLocator {
    @Override
    public <T> T getInstance(Class<T> clazz) {
        try {
            return clazz.newInstance(); // <-- just create a new instance of a class on every method call
        } catch (InstantiationException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
```
In jersey-example `SampleJsonServiceLocator` is used (https://github.com/katharsis-project/katharsis-examples/blob/master/jersey-example/src/main/java/io/katharsis/example/jersey/JerseyApplication.java#L19) but at the beginning you can try to make something like this
```java
@ApplicationPath("/")
public class JerseyApplication extends ResourceConfig {

    public static final String APPLICATION_URL = "http://localhost:8080/";

    public JerseyApplication() {

        MyDatastoreManager manager = // initialize the manager

        property(KatharsisProperties.RESOURCE_SEARCH_PACKAGE, "io.katharsis.example.jersey.domain");
        property(KatharsisProperties.RESOURCE_DEFAULT_DOMAIN, APPLICATION_URL);
        register(new KatharsisFeature(new ObjectMapper(), new JsonServiceLocator(){

            @Override public <T> T getInstance(Class<T> clazz) {
                if (TaskRepository.class.equals(clazz)) {
                    return new TaskRepository(manager.getDatastore());
                }
                try {
                    return clazz.newInstance();
                } catch (IllegalAccessException | InstantiationException e) {
                    throw new RuntimeException(e);
                }
            }
        }));
    }
}
```

**Comment by nevson** [comment]
@meshuga Awesome, thanks a lot for your detailed answer! I'll give it tomorrow a try. Btw. the wildfly example seems to be the most advanced one. Would you recommend the wildfly solution over the jersey or plain dropwizard one?

**Comment by meshuga** [comment]
That's a tricky question ;)
For beginners I would recommend Dropwizard.
