### ISSUE TITLE
Support for Java 7

### ISSUE THREAD

**Issue by nevson** [katharsis-project/katharsis-core#67]
For my target environment sadly Java 8 isn't available yet but Katharsis depends on Java 8 as is uses some new features like `::`. Also the license model starting from Java 8 has changes so that you've to pay now license fees in case of commercial products. Is there any chance that Katharsis will support also Java 7?

**Comment by sglanzer** [comment]
This would also help me a lot

**Comment by meshuga** [comment]
clone of #48 
As for now I don't want to spend time to support Java 7. You could try https://github.com/orfjackal/retrolambda with http://mvnrepository.com/artifact/net.sourceforge.streamsupport/streamsupport to make Java 7-compatible packages.

**Comment by sglanzer** [comment]
Sounds reasonable, thanks for the reply

**Comment by datagitlies** [comment]
Using [retrolambda](https://github.com/orfjackal/retrolambda) and [streamsupport](http://sourceforge.net/projects/streamsupport/) I was able to backport katharsis-core to run on Java 7 @nevson @sglanzer you can see the result in our fork here https://github.com/StateFarmIns/katharsis-core/

**Comment by sglanzer** [comment]
@datagitlies Excellent - I've got some people to show this to!

**Comment by datagitlies** [comment]
@sglanzer take a look at Issue #48 for the latest information
