### ISSUE TITLE
Add meta field in top-level JSON

### ISSUE THREAD

**Issue by meshuga** [katharsis-project/katharsis-core#7]
Add *meta* field in top-level JSON as defined in http://jsonapi.org/format/#document-meta

**Comment by JliptonRTR** [comment]
Hey, has any progress been made here? I would love to be able to write to the meta field on a call to a repository function. My particular use case is defining the schema returned by a findAll.

**Comment by meshuga** [comment]
Yeah, that might be a good thing, providing meta information per repository/model. I think the next version will support it :)

**Comment by SitalAtDominos** [comment]
:+1:

**Comment by elennick** [comment]
just wanted to check in... any progress on this? we have run into a few cases in the past few days where we want to use the meta field with katharsis... thanks!

**Comment by meshuga** [comment]
I have some idea to create an optional interface like
```java
public interface MetaRepository<T> {
  MetaInformation getMetaInformation(T resource);
  MetaInformation getMetaInformation(Iterable<T> resources);
}
```
which could be implemented along with ResourceRepository and if a repository implements that interface, after each create, read or update operation, a call to one of those methods will be made, but I don't know if it could be a suitable solution for most of the usages. @elennick @SitalAtDominos What do you think?

**Comment by elennick** [comment]
@meshuga seems reasonable... id be ok with just having

```
MetaInformation getMetaInformation(Iterable<T> resources);
```

...and still using that method with an iterable with only 1 resource in it if there is only one... will make things a bit less cluttered.

What do you envision the MetaInformation object would be designed? Similar to how resource objects are defined?

**Comment by meshuga** [comment]
No, it'll be an interface without any method.

**Comment by meshuga** [comment]
I created two interfaces (`MetaRepository` and `ResourceMetaRepository`). Tomorrow I'll finish it.
