### ISSUE TITLE
Using ObjectMapper as a standalone

### ISSUE THREAD

**Issue by corrspt** [katharsis-project/katharsis-core#74]
Hey, first of all I'd like to thank you guys for the effort on the Library.

I'm playing with a Play Framework app (Play 2.4.2). And I was trying to integrate Katharsis (0.9.3) with it but I can't seem to figure the way I should do it from the examples.

In that sense I thought that maybe I could just use whatever you guys do with the Jackson library to get the behavior I want as a standalone. I've found a [test which seemed to be exactly](https://github.com/katharsis-project/katharsis-core/blob/a809dc472d25ebac34cf0d302003017d2fe175d8/src/test/java/io/katharsis/jackson/BaseSerializerTest.java) what I've wanted but when I tried it in a simple Java main, it does not spit out a JSONAPI compatible JSON, but a regular JSON.

```java
ObjectMapper sut = null;
		
ResourceRegistryBuilder registryBuilder = new ResourceRegistryBuilder(new SampleJsonServiceLocator(), new ResourceInformationBuilder());
ResourceRegistry resourceRegistry = registryBuilder.build("test.models", "http://localhost:9000/api");

JsonApiModuleBuilder jsonApiModuleBuilder = new JsonApiModuleBuilder();

 sut = new ObjectMapper();
 sut.registerModule(jsonApiModuleBuilder.build(resourceRegistry));
               
 PostJSON p = new PostJSON();
 p.setId("someId");
 p.setName("Some Name");
        
EntityJSON j = new EntityJSON();
j.setId(UUID.randomUUID());
j.setName("John");
j.setPost(p);
        
System.out.println(sut.writeValueAsString(j));

```

Do notice that my EntityJSON.java file is annotated (correctly I hope)

```java
@JsonApiResource(type = "entities")
public class EntityJSON {
	
	@JsonApiId
	private UUID id;
	
	private String name;

    //getters and setters
}
```

I did, however find that if I changed my println to 
```java
RequestParams req = new RequestParams(sut);
System.out.println(sut.writeValueAsString(new Container(j,req)));
```
I get
```json
{
  "type": "entities",
  "id": "6f510d4d-321a-4c6e-bd5b-4a9e24eaa71a",
  "attributes": {
    "name": "John"
  },
  "relationships": {
    "post": {
      "links": {
        "self": "http://localhost:9000/api/entities/6f510d4d-321a-4c6e-bd5b-4a9e24eaa71a/relationships/post",
        "related": "http://localhost:9000/api/entities/6f510d4d-321a-4c6e-bd5b-4a9e24eaa71a/post"
      },
      "data": {
        "type": "posts",
        "id": "batata"
      }
    }
  },
  "links": {
    "self": "http://localhost:9000/api/entities/6f510d4d-321a-4c6e-bd5b-4a9e24eaa71a"
  }
}
```

That it does indeed to what I want :) But I wanted to know a few things

* Can I get rid of the "links"? section
* Is there a better way of doing this as a standalone? Should I use the container, that requires the "RequestParameters"
* Do I really need to implement the resourceRepository interface? It just needs to exits apparently (all my methods returning null seem to do the trick)
* Would there be a way to integrate with the Play framework? Or maybe having a core-module that Just does the JSONAPI parsing/serializing and then having other projects that do the dropwizard, wildfly integration?

Thanks in advance :+1:

**Comment by meshuga** [comment]
1. It would be possible to hide `links` section, but I don't think it's something crucial ;)
2. But what in case of inclusion of elements, that is you want to include some other resources? I think that the example you showed is the most elegant way as for now.
3. https://github.com/katharsis-project/katharsis-core/issues/53 0.9.4 should handle it
4. I've played with Play framework for too short to advise you anything but been thinking about katharsis-client, some new project that will have support for things like that (https://github.com/katharsis-project/katharsis-core/issues/68)

**Comment by elennick** [comment]
@corrspt we have a basic implementation of katharsis in our Play 2.4.2 application. What we did is create a builder around the katharsis stuff that let you say something like this in a controller:

```
String jsonResponse = katharsisResponseBuilder.build(request());
return status(200, jsonResponse);
```

You can create a route that does wildcard matching to a controller method to catch everything that routes to a certain base url like this:

```
GET /api/*resource @com.mypackage.controllers.MyJsonApiController.getJsonApiResult(resource)
```

Anyhow if you use the code you already posted above you should be able to extract stuff like the query params and resource url and the request body out of the request() that comes with a play request. It's not perfect but it's a decent first approach we're iterating on.

**Comment by corrspt** [comment]
@meshuga 

Thanks for replying. For the record I'm trying out Katharsis with EmberJS and Ember Data (and Play as backend)

1) I might have jumped to soon with that question about links (as I don't know the JSONAPI format very well) you are probably right that they should be there.
2) I'm not entirely sure I understood what you said with "what about including other resources". Sorry
3) Cool, thanks! When should I expect a 0.9.4 on maven central? (or am I better of building katharsis on my local machine and including it as jar?). Another thinks that interests me is the possibility of having the annotations on getters (to have wrapper objects) but I've seen in a commit/issue somewhere that 0.9.4 should have that, thanks :)
4) Thanks for pointing it out

@elennick 
Thanks for sharing the information, I was kind of expecting to have to declare all my routes manually and creating controllers for each of them to properly process the requests, but your post got me wondering if I really need to do that for most of the "crudish" operations. :+1:

**Comment by meshuga** [comment]
2. I mean http://jsonapi.org/format/#document-compound-documents and http://jsonapi.org/format/#fetching-includes - you can specify to add custom resources
3. See https://github.com/katharsis-project/katharsis-core/issues/70 :) 
I think soon version 0.9.4 should be released, but first I'd like to close https://github.com/katharsis-project/katharsis-core/issues/53

**Comment by elennick** [comment]
@corrspt if you use the wildcard mechanism above and pass the correct resource from the url to the katharsis request dispatcher, you should only ever have to write that one controller and never another ever again... katharsis repositories essentially become your controller layer in place of a Play controller and resources essentially become binders that define your response format

**Comment by corrspt** [comment]
@meshuga Thanks a lot for the comments, really looking forward for issues #70 and #53 to be closed :)

@elennick - I see what you mean. I'm going to need #70 to be closed, but I'll explore that solution. Thanks!
