### ISSUE TITLE
Accessor method called twice with @JsonApiToOne and @JsonApiIncludeByDefault

### ISSUE THREAD

**Issue by danielmischler** [katharsis-project/katharsis-core#75]
I have the situation where I do some processing in an accessor method for a field annotated with
@JsonApiToOne and @JsonApiIncludeByDefault.

The appropriate accessor method is now called twice i.e. doubling the processing time.

The behavior can be reproduced by adding the following to Task.java of the jersey-example

```
@JsonApiToOne
@JsonApiIncludeByDefault
private Project project;
```

Is this a bug or required behavior?

**Comment by meshuga** [comment]
This is desired behavior. The first time it's called to get the relationship resource and the second to get information about the resource to be included.
