### ISSUE TITLE
dropwizard-simple-sample only return 500 internal server when there are problems creating a resource

### ISSUE THREAD

**Issue by sweco-semtne** [katharsis-project/katharsis-core#81]
This maybe isn't related to katharsis-core but it seems that the only error that is being returned to the client when trying to create a new resource is a 500 internal server error.

**Comment by meshuga** [comment]
Using Katharsis you can create a mapper which will implement `JsonApiExceptionMapper<RuntimeException>` that will map unexpected exceptions to JSON API error responses.
You can take a look at http://katharsis.io/docs in **Error Handling** section.
