### ISSUE TITLE
Data field of relationships always null or empty

### ISSUE THREAD

**Issue by joewhite101** [katharsis-project/katharsis-core#87]
When a relationship is returned the data : {} embedded in the relationship object is always null or empty. It should contain an id and a type. For example using this example:
`https://github.com/katharsis-project/katharsis-examples/tree/master/spring-boot-simple-example`

A call to this URL `http://localhost:8080/tasks`

Returns this relationship:

    relationships": {
        "project": {
        "links": {
            "self": "http://localhost:8080/tasks/1/relationships/project",
            "related": "http://localhost:8080/tasks/1/project"
        },
       "data": null
       }
    }

The data section of the relationship should be:

    "data" : {type: "project", id: 1}

**Comment by meshuga** [comment]
Well, `spring-boot-simple-example` just shows how to integrate Spring with Katharsis. There's no repository logic implemented - https://github.com/katharsis-project/katharsis-examples/blob/master/spring-boot-simple-example/src/main/java/io/katharsis/example/springboot/simple/domain/repository/TaskToProjectRepository.java

But it should work as long as you implemented resource repositories and a relationship repository.
