### ISSUE TITLE
Add ability to hide to-many relationships

### ISSUE THREAD

**Issue by meshuga** [katharsis-project/katharsis-core#91]
When showing a resource, it should be possible to hide to-many relationships. 
See: https://github.com/katharsis-project/katharsis-servlet/issues/5#issuecomment-138805408

**Comment by peterlau** [comment]
Hi, I noticed that this change was undone in
https://github.com/katharsis-project/katharsis-core/commit/f84c728ccdfdd82fceb698a3d280c38568dd199f

and now the lazy attribute is not being read anywhere else in the code. 

What is the recommended way to load a resource without loading it's relationships?

**Comment by meshuga** [comment]
thanks for the notice!
