### ISSUE TITLE
Saving a Entity with a Relationship in one step, how to

### ISSUE THREAD

**Issue by corrspt** [katharsis-project/katharsis-core#95]
Hey guys,

I'm wanted to ask how I should do this:

I have a model PositionAPI which has a relation to a model IndustryCodeAPI through field `industryCode`, which is required (meaning the database has a *not null* constraint in the industry_code_id column) 
I want to save my PositionAPI with a reference to the IndustryCodeAPI, but I get an error from the database that industry_code_id is null. I've found out why, but I don't see how to fix it.

These are my models:
```java
@JsonApiResource(type = "positions")
public class PositionAPI {

	@Transient
	@JsonIgnore
	private transient Position position;
	
	public PositionAPI() {
		this.position = new Position();
	}
	
	public PositionAPI(Position position) {
		this.position = position;
	}
	
	@JsonApiId
	public Long getId() {
		return position.getId();
	}
	
	public String getCode() {
		return position.getCode();
	}

	public void setCode(String code) {
		position.setCode(code);
	}

	@JsonApiToOne
	public IndustryCode getIndustryCode() {
		return position.getIndustryCode();
	}

	public void setIndustryCode(IndustryCodeAPI industrycode) {
		position.setIndustryCode(industrycode.getOriginal());
	}

	@JsonIgnore
	public Position getOriginal(){
		return position;
	}
	
}

@JsonApiResource(type = "industry-codes")
public class IndustryCodeAPI {

	@Transient
	@JsonIgnore
	private transient IndustryCode industryCode;
	
	public IndustryCodeAPI() {
		industryCode = new IndustryCode();
	}
	
	public IndustryCodeAPI(IndustryCode code) {
		industryCode = code;
	}
	
	@JsonApiId
	public Long getId() {
		return industryCode.getId();
	}

	public String getCode() {
		return industryCode.getCode();
	}

	public void setCode(String code) {
		industryCode.setCode(code);
	}

	public String getRegion() {
		return industryCode.getRegion();
	}

	public void setRegion(String region) {
		industryCode.setRegion(region);
	}
	
	@JsonIgnore
	public IndustryCode getOriginal(){
		return industryCode;
	}
	
	
}
```

I've implemented the  ResourceRepository for both of them and Implemented a RelationtshipRepository

```java
public class PositionRelantionshipRepository implements
		RelationshipRepository<PositionAPI, Long, IndustryCodeAPI, Long> {

	@Override
	public void setRelation(PositionAPI source, Long targetId,
			String fieldName) {
		IndustryCode code = IndustryCode.find.byId(targetId);
		source.setIndustryCode(new IndustryCodeAPI(code));
	}
        //other methods
```

If you're wondering about the Model vs ModelAPI names, it's just that I have JPA entities but wrap them around an ModelAPI to have my annotations on those classes and not mix them. This is the JSONAPI data sent by the client (POST to Save this new Position)

```json
{
  "data": {
    "attributes": {
      "code": "Test"
    },
    "relationships": {
      "industry-code": {
        "data": {
          "type": "industry-codes",
          "id": "8"
        }
      }
    },
    "type": "positions"
  }
}
```

Checking katharsis code I got to the point where in `ResourcePost` there's this:

```
//lines 63-67
setAttributes(dataBody, resource, registryEntry.getResourceInformation());
ResourceRepository resourceRepository = registryEntry.getResourceRepository();
Object savedResource = resourceRepository.save(resource);
saveRelations(savedResource, registryEntry, dataBody);
```

So the object is saved before relations are set.

My question is, how can I save PositionAPI with a reference to IndustryCodeAPI, or do I have to make my constraints not null, save the Position without the references, then use the relationship repository to set the relation and then save the instance on the relationship repository?  (which feels weird to me because then I would have to save each instance for each relation is has).

Any ideas?

There's also another thing I might be doing wrong, because I'm using the play framework and there's no integration with it on the documentation (I've created an issue before), I've had to dig through the source code to find how to reply to requests:

This is what my controller which handles all requests for JSONAPI looks like

```java
public Result getJsonApiResult(String resource) throws Exception {
		
		ResourceInformationBuilder resourceInformationBuilder = new ResourceInformationBuilder(new ResourceFieldNameTransformer());
        ResourceRegistryBuilder registryBuilder = new ResourceRegistryBuilder(new ServiceLocator(), resourceInformationBuilder);
        resourceRegistry = registryBuilder.build("com.project.api", "http://localhost:9000/api");
        
        String path = resource;
        Request req = request();
        String requestType = req.method();
        

        PathBuilder pathBuilder = new PathBuilder(resourceRegistry);
        TypeParser typeParser = new TypeParser();
        
        JsonApiModuleBuilder jsonApiModuleBuilder = new JsonApiModuleBuilder();
        ObjectMapper om = new ObjectMapper();
        om.registerModule(jsonApiModuleBuilder.build(resourceRegistry));
        
        ControllerRegistryBuilder controllerBuilder = new ControllerRegistryBuilder(resourceRegistry, typeParser, om);
        ControllerRegistry controllerRegistry = controllerBuilder.build();
        
        ExceptionMapperRegistryBuilder b = new ExceptionMapperRegistryBuilder();
        RequestDispatcher sut = new RequestDispatcher(controllerRegistry, b.build("com.project.api.mappers"));

        JsonPath jsonPath = pathBuilder.buildPath(path);
        
        RequestBody body = null;
        if ("POST".equalsIgnoreCase(requestType) 
        	|| "PUT".equalsIgnoreCase(requestType) 
        	|| "PATCH".equalsIgnoreCase(requestType)
        	){
        	play.mvc.Http.RequestBody playBody =  req.body();
        	String raw =  new String(playBody.asRaw().asBytes());
        	body = om.readValue(raw, RequestBody.class);
        }
        
        Map<String,String> queryParams = new HashMap<>();
        RequestParamsBuilder paramsBuilder = new RequestParamsBuilder(om);
        JSONAPIParameterParser paramParser = new JSONAPIParameterParser();
        
        Map<String,String> filters = paramParser.parseFilters(req.queryString());
        queryParams.put(RestrictedQueryParamsMembers.filter.name(), om.writeValueAsString(filters));
        Map<String,SortingValues> sorting = paramParser.parseSorting(req.queryString());
        queryParams.put(RestrictedQueryParamsMembers.sort.name(), om.writeValueAsString(sorting));
        Map<String,String> paging = paramParser.parsePaging(req.queryString());
        queryParams.put(RestrictedQueryParamsMembers.page.name(), om.writeValueAsString(paging));
        
        BaseResponse<?> response = sut.dispatchRequest(jsonPath, requestType, paramsBuilder.buildRequestParams(queryParams),  body);
        crossOrigin.applyCrossOrigin(response());
        if (response != null){
        	String json = om.writeValueAsString(response);
        	return status(response.getHttpStatus(), json);      	
        } else {
        	if ("DELETE".equalsIgnoreCase(requestType)){
        		return status(204);
        	}
        }
        return status(200);
        
        
	}
```

Thanks a lot for the project

**Comment by meshuga** [comment]
The resource creation mechanism first save the resource, then, using `RelationshipRepository`, it sets up the relationships. Thanks for the case, it would be more suitable to just build the desired object with relations and then save it.

**Comment by corrspt** [comment]
Thanks for the quick reply @meshuga 

I'm not quite sure if I understood what you said with `it would be more suitable to just build the desired object with relations and then save it.`. Are you talking on my end or on the katharsis end? 

If it's on my end, how would I be able to setup the relations before the object is saved?

**Comment by meshuga** [comment]
I meant on Katharsis level.

**Comment by corrspt** [comment]
Oh, ok. Can I do anything to help?

At the moment I'll workaround the issue by removing my constraints and saving each time on the setRelation method! Thanks again for the very quick reply. An awesome project you guys have here!

On a side-note (if you want I can make a separate issue), may I trouble you to look at my "getJsonAPI" method and tell me if there are things there that are wrong? Things have been working but I've found lots of issue because I didn't know how to setup all the Katharsis parts and pieces.

**Comment by meshuga** [comment]
Why your method doesn't catch possible exceptions?

**Comment by corrspt** [comment]
Well, I thought that all exceptions had to be handled through Katharsis itself (with the ExceptionMappers). At least those regarding the my JSONAPI

What I've been doing is registering those Mappers for the various exceptions I've been getting (I'm at the early beginning of my app). I only have two mappers at the moment, but I believe they'll grow. 

I am thinking incorrectly here?

**Comment by meshuga** [comment]
Take a look at `dispatchRequest` method in `KatharsisFilter` class in `katharsis-rs` https://github.com/katharsis-project/katharsis-rs/blob/development/src/main/java/io/katharsis/rs/KatharsisFilter.java#L82
For example, a `KatharsisMatchingException` can be thrown when Katharsis won't be able to parse the message. In that case you should return 404 message. Additionally, it's possible for Katharsis to throw `KatharsisMappableException`, so you should handle that too.

**Comment by corrspt** [comment]
Hum, thanks a lot for the tip. I'll look into that file carefully by tomorrow! :+1:

**Comment by corrspt** [comment]
Hey @meshuga, first of all thanks a lot for the commits that fix this issue.

I would like to add though that the [ResourcePatch class suffers from the same problem] (https://github.com/katharsis-project/katharsis-core/blob/740d0aef423c55feeaa0ce0e247dfc0023406901/src/main/java/io/katharsis/dispatcher/controller/resource/ResourcePatch.java#L67-L68). If I could trouble you to fix this as well it would be great :+1: 

Again thanks for the efforts with this Library! Also, with version 1.0 I'm also taking advantage of the MetaRepository now having access to the request parameters!

**Comment by meshuga** [comment]
You made me think about RelationshipRepository. I did that to make use of those types of repos, but even for me the mechanism of repos is not intuitive. I'll create a new issue to address that.

**Comment by corrspt** [comment]
I've only implemented one RelationshipRepository so far.

I'm just beginning my app, but I envision that I will need *lots* of them as I have some entities that have relationships with lots of other entities. I don't have a good suggestion to give, but if something comes to mind, I'll try to contribute on that issue.

Thanks again @meshuga

**Comment by meshuga** [comment]
https://github.com/katharsis-project/katharsis-core/issues/99
